/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;
import javax.swing.DefaultListModel;

import logica.proponente;
import logica.categoria;

import logica.propuesta;

import java.util.Date;
import java.util.Calendar; //para pasar a una Date datos
import java.util.HashSet;
import java.util.Set;

import javax.swing.JOptionPane;

import logica.estadoPropuesta;

public class PanelIngreso extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngreso
     */
    
    javax.swing.JPanel contenido;
    java.awt.CardLayout c1;
    
    private ictrl ic;
    DefaultListModel<String> modelo = new DefaultListModel<>(); //
    DefaultListModel<String> modelo2 = new DefaultListModel<>();
    
    private byte[] imagenBytes = null;
    
    public PanelIngreso(ictrl ic, javax.swing.JPanel contenido, java.awt.CardLayout c1) {
        initComponents();
        this.ic = ic;
        
        this.contenido = contenido;
        this.c1 = c1;
        
        ListaProponentes.setModel(modelo);
        for(proponente p : ic.listarProponentes()){
        modelo.addElement("Nickname: " + p.getNickname() + " | Nombre: " + p.getNombre() + " | Apellido: " + p.getApellido());
        }
        
        ListaTipo.setModel(modelo2);
        for(categoria c : ic.listarCategoria()){
        modelo2.addElement("Categoria: " + c.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProponentes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaTipo = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextoTitulo = new javax.swing.JTextField();
        TextoDescripcion = new javax.swing.JTextField();
        TextoLugar = new javax.swing.JTextField();
        TextoValor = new javax.swing.JTextField();
        TextoMonto = new javax.swing.JTextField();
        labelFoto = new javax.swing.JLabel();
        BotonImagen = new javax.swing.JButton();
        SpinnerDia = new javax.swing.JSpinner();
        SpinnerMes = new javax.swing.JSpinner();
        SpinnerAno = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        botonAmbas = new javax.swing.JRadioButton();
        botonEntradaGratis = new javax.swing.JRadioButton();
        botonPorcentaje = new javax.swing.JRadioButton();
        botonIngresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("INGRESO PROPUESTA");

        ListaProponentes.setBackground(new java.awt.Color(255, 255, 255));
        ListaProponentes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaProponentes.setForeground(new java.awt.Color(16, 32, 56));
        ListaProponentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListaProponentes);

        ListaTipo.setBackground(new java.awt.Color(255, 255, 255));
        ListaTipo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaTipo.setForeground(new java.awt.Color(16, 32, 56));
        ListaTipo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaTipo.setToolTipText("");
        jScrollPane2.setViewportView(ListaTipo);

        jPanel1.setBackground(new java.awt.Color(255, 240, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("Titulo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("Descripcion:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("Lugar:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(16, 32, 56));
        jLabel6.setText("Valor entrada:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(16, 32, 56));
        jLabel7.setText("Monto necesario:");

        TextoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TextoTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(16, 32, 56));
        TextoTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTituloActionPerformed(evt);
            }
        });

        TextoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        TextoDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoDescripcion.setForeground(new java.awt.Color(16, 32, 56));
        TextoDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        TextoLugar.setBackground(new java.awt.Color(255, 255, 255));
        TextoLugar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoLugar.setForeground(new java.awt.Color(16, 32, 56));
        TextoLugar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        TextoValor.setBackground(new java.awt.Color(255, 255, 255));
        TextoValor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoValor.setForeground(new java.awt.Color(16, 32, 56));
        TextoValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        TextoMonto.setBackground(new java.awt.Color(255, 255, 255));
        TextoMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoMonto.setForeground(new java.awt.Color(16, 32, 56));
        TextoMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        BotonImagen.setBackground(new java.awt.Color(16, 32, 56));
        BotonImagen.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonImagen.setForeground(new java.awt.Color(255, 255, 255));
        BotonImagen.setText("INGRESAR IMAGEN");
        BotonImagen.setBorderPainted(false);
        BotonImagen.setContentAreaFilled(false);
        BotonImagen.setOpaque(true);
        BotonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImagenActionPerformed(evt);
            }
        });

        SpinnerDia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        SpinnerDia.setBorder(null);
        SpinnerDia.setOpaque(false);

        SpinnerMes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        SpinnerMes.setBorder(null);
        SpinnerMes.setOpaque(false);

        SpinnerAno.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerAno.setModel(new javax.swing.SpinnerNumberModel(2025, 2025, 2030, 1));
        SpinnerAno.setBorder(null);
        SpinnerAno.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 32, 56));
        jLabel5.setText("Fecha:");

        botonAmbas.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(botonAmbas);
        botonAmbas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonAmbas.setForeground(new java.awt.Color(16, 32, 56));
        botonAmbas.setText("Ambas");
        botonAmbas.setContentAreaFilled(false);

        botonEntradaGratis.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(botonEntradaGratis);
        botonEntradaGratis.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonEntradaGratis.setForeground(new java.awt.Color(16, 32, 56));
        botonEntradaGratis.setText("Entrada Gratis");
        botonEntradaGratis.setContentAreaFilled(false);

        botonPorcentaje.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(botonPorcentaje);
        botonPorcentaje.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonPorcentaje.setForeground(new java.awt.Color(16, 32, 56));
        botonPorcentaje.setText("Porcentaje");
        botonPorcentaje.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(TextoDescripcion)
                                    .addComponent(TextoLugar)
                                    .addComponent(TextoValor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(SpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEntradaGratis)
                        .addGap(18, 18, 18)
                        .addComponent(botonPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(botonAmbas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonImagen)
                        .addGap(26, 26, 26)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonImagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEntradaGratis)
                            .addComponent(botonPorcentaje)
                            .addComponent(botonAmbas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        botonIngresar.setBackground(new java.awt.Color(16, 32, 56));
        botonIngresar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("INGRESAR PROPUESTA");
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setOpaque(true);
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 32, 56));
        jLabel8.setText("PROPONENTES");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(16, 32, 56));
        jLabel9.setText("CATEGORIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel9))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(botonIngresar)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonIngresar)
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTituloActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        //almaceno todo y doy de alta una propuesta
    proponente seleccionado = null;
    int i = ListaProponentes.getSelectedIndex();
    if(i >= 0){
    seleccionado = ic.listarProponentes().get(i);
    }
    
    String titulo = TextoTitulo.getText();
    String descripcion = TextoDescripcion.getText();
    String tipoEspectaculo = null; 
    tipoEspectaculo = ListaTipo.getSelectedValue();
    String lugar = TextoLugar.getText();
    int dia = (int) SpinnerDia.getValue();
    int mes = (int) SpinnerMes.getValue();
    int anio = (int) SpinnerAno.getValue();
    Calendar cal = Calendar.getInstance();
    cal.set(anio, mes - 1, dia);
    Date fecha = cal.getTime();
    
    byte[] imagen = imagenBytes;
    
    //float precioEntrada = 10; //CORREGIR ESTO TOMAR DEL USUARIO
    //float montoNecesario = 10; //CORREGIR ESTO TOMAR DEL USUARIO
    
    String p = TextoValor.getText();
    Float precio = Float.parseFloat(p);
    
    String m = TextoMonto.getText();
    Float monto = Float.parseFloat(m);
    
        if(seleccionado == null){
        JOptionPane.showMessageDialog(this, "Selecciona el Proponente.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        return;
        }
        if(tipoEspectaculo == null){
        JOptionPane.showMessageDialog(this, "Selecciona el tipo.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        return;
        }
        if(titulo.isEmpty()){
        JOptionPane.showMessageDialog(this, "El Titulo es obligatorio.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        TextoTitulo.requestFocus();
        return;
        }
        if(descripcion.isEmpty() || tipoEspectaculo.isEmpty() || lugar.isEmpty()){
        JOptionPane.showMessageDialog(this, "Completa Descripcion, tipo Espectaculo y lugar.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        //verificar existencia. 
        for(propuesta prop : ic.listarPropuestas()){
        if(prop.getTitulo().equalsIgnoreCase(titulo)){
        JOptionPane.showMessageDialog(this, "El Titulo ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
        return;
        }
        }
        
        if(botonEntradaGratis.isSelected() || botonPorcentaje.isSelected() || botonAmbas.isSelected()){
            //no me funcionaba poniendoles ! (negado) no se por que. por ahora queda asi.
        }else{
        JOptionPane.showMessageDialog(this, "Selecciona Tipo Retorno.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        }
        
        //tipo ret elegido.
        String tipoRetorno = null;
        if(botonEntradaGratis.isSelected()){
        tipoRetorno = "Entrada";
        }
        if(botonPorcentaje.isSelected()){
        tipoRetorno = "Porcentaje";
        }
        if(botonAmbas.isSelected()){
        tipoRetorno = "Ambas";
        }
        
        JOptionPane.showMessageDialog(this, "Propuesta ingresada con exito.", "Operacion exitosa", JOptionPane.WARNING_MESSAGE);
        
        //ahora si
        
        ic.altaPropuesta(seleccionado, titulo, descripcion, tipoEspectaculo, lugar, fecha, precio, monto, tipoRetorno, imagenBytes, estadoPropuesta.INGRESADA);
    
        c1.show(contenido, "principal");
    
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void BotonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImagenActionPerformed
        // TODO add your handling code here:
        
        //deberia abrir una ventana con el file chooser
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Seleccionar imagen.");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagenes (JPG, PNG, JPEG)", "jpg", "jpeg", "png"));
        chooser.showOpenDialog(jPanel1);
        
        java.io.File f = chooser.getSelectedFile();
        if(f == null || !f.exists()){
        javax.swing.JOptionPane.showMessageDialog(this, "No se selecciono un archivo valido.", "Atencion", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        try{
            java.awt.image.BufferedImage imagen = javax.imageio.ImageIO.read(f);
            if(imagen == null){
            javax.swing.JOptionPane.showMessageDialog(this, "El archivo no es una imagen valida.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
            }
            
        //tamano de destino
        int boxW = labelFoto.getWidth();
        int boxH = labelFoto.getHeight();
        if (boxW <= 0 || boxH <= 0) { boxW = 160; boxH = 160; }

        //mantener proporciones
        int w = imagen.getWidth(), h = imagen.getHeight();
        double scale = Math.min((double) boxW / w, (double) boxH / h);
        int nw = Math.max(1, (int) Math.round(w * scale));
        int nh = Math.max(1, (int) Math.round(h * scale));

        // escalar con calidad
        java.awt.image.BufferedImage scaled = new java.awt.image.BufferedImage(nw, nh, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D g2 = scaled.createGraphics();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,      java.awt.RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,   java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.drawImage(imagen, 0, 0, nw, nh, null);
        g2.dispose();
        
        //mostrar en el JLabel
        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setIcon(new javax.swing.ImageIcon(scaled));
        
        labelFoto.setVisible(true);
        labelFoto.revalidate();
        labelFoto.repaint();;

        java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
        javax.imageio.ImageIO.write(scaled, "png", baos);
        baos.flush();
        imagenBytes = baos.toByteArray();
        baos.close();
        
        }catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen.\n" + e.getMessage(),"Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonImagen;
    private javax.swing.JList<String> ListaProponentes;
    private javax.swing.JList<String> ListaTipo;
    private javax.swing.JSpinner SpinnerAno;
    private javax.swing.JSpinner SpinnerDia;
    private javax.swing.JSpinner SpinnerMes;
    private javax.swing.JTextField TextoDescripcion;
    private javax.swing.JTextField TextoLugar;
    private javax.swing.JTextField TextoMonto;
    private javax.swing.JTextField TextoTitulo;
    private javax.swing.JTextField TextoValor;
    private javax.swing.JRadioButton botonAmbas;
    private javax.swing.JRadioButton botonEntradaGratis;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JRadioButton botonPorcentaje;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFoto;
    // End of variables declaration//GEN-END:variables
}
