/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;
import logica.colaborador;
import logica.propuesta;
import logica.colaboracion;

import java.util.List;
import javax.swing.DefaultListModel;

public class PanelConsultaColaborador extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultaColaborador
     */
    
    ictrl ic;
    
    List lista = null;
    DefaultListModel<String> modelo = new DefaultListModel<>();
    
    DefaultListModel modelo2 = new DefaultListModel();
    
    public PanelConsultaColaborador(ictrl ic) {
        initComponents();
        this.ic = ic;
        ListaColaboradores.setModel(modelo);
        for(colaborador c : ic.listarColaboradores()){
        modelo.addElement("Nickname: " + c.getNickname() + " | Nombre: " + c.getNombre() + " | Apellido: " + c.getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaColaboradores = new javax.swing.JList<>();
        PanelDatos = new javax.swing.JPanel();
        LabelFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextoNickname = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoApellido = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textoNickname = new javax.swing.JTextField();
        textoEstado = new javax.swing.JTextField();
        textoRecaudado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("CONSULTA COLABORADOR");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("COLABORADORES");

        ListaColaboradores.setBackground(new java.awt.Color(255, 255, 255));
        ListaColaboradores.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaColaboradores.setForeground(new java.awt.Color(16, 32, 56));
        ListaColaboradores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaColaboradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaColaboradores);

        PanelDatos.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("Nickname:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 32, 56));
        jLabel5.setText("Apellido:");

        TextoNickname.setEditable(false);
        TextoNickname.setBackground(new java.awt.Color(255, 255, 255));
        TextoNickname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoNickname.setForeground(new java.awt.Color(16, 32, 56));
        TextoNickname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNicknameActionPerformed(evt);
            }
        });

        TextoNombre.setEditable(false);
        TextoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoNombre.setForeground(new java.awt.Color(16, 32, 56));
        TextoNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        TextoApellido.setEditable(false);
        TextoApellido.setBackground(new java.awt.Color(255, 255, 255));
        TextoApellido.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoApellido.setForeground(new java.awt.Color(16, 32, 56));
        TextoApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoNombre)
                    .addComponent(TextoNickname)
                    .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(51, 51, 51))
        );

        jPanel1.setOpaque(false);

        textoNickname.setEditable(false);
        textoNickname.setBackground(new java.awt.Color(255, 255, 255));
        textoNickname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoNickname.setForeground(new java.awt.Color(16, 32, 56));
        textoNickname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoEstado.setEditable(false);
        textoEstado.setBackground(new java.awt.Color(255, 255, 255));
        textoEstado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoEstado.setForeground(new java.awt.Color(16, 32, 56));
        textoEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstadoActionPerformed(evt);
            }
        });

        textoRecaudado.setEditable(false);
        textoRecaudado.setBackground(new java.awt.Color(255, 255, 255));
        textoRecaudado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoRecaudado.setForeground(new java.awt.Color(16, 32, 56));
        textoRecaudado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        listaPropuestas.setBackground(new java.awt.Color(255, 255, 255));
        listaPropuestas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaPropuestas.setForeground(new java.awt.Color(16, 32, 56));
        listaPropuestas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropuestasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaPropuestas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textoRecaudado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNicknameActionPerformed

    private void ListaColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaColaboradoresMouseClicked
        // TODO add your handling code here:
        colaborador seleccionado = null;
        int i = ListaColaboradores.getSelectedIndex();
        if(i>=0){
        seleccionado = ic.listarColaboradores().get(i);
        }
        TextoNickname.setText(seleccionado.getNickname());
        TextoNombre.setText(seleccionado.getNombre());
        TextoApellido.setText(seleccionado.getApellido());
        LabelFoto.setIcon(seleccionado.bytesAIcon());
        
        //muestro las propuestas q colaboro. (SI TIENE) a ver si puedo arreglar el error .
        modelo2.clear();
        listaPropuestas.setModel(modelo2);
        if(!ic.listarColaboraciones().isEmpty()){
        for(colaboracion c : ic.listarColaboraciones()){
            if(c.getColaborador() == null) continue;
        if(c.getColaborador().getNickname().equalsIgnoreCase(seleccionado.getNickname())){
        modelo2.addElement(c.getPropuesta().getTitulo());
        }
        }
        }
        
    }//GEN-LAST:event_ListaColaboradoresMouseClicked

    private void textoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstadoActionPerformed

    private void listaPropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropuestasMouseClicked
        // TODO add your handling code here:

        propuesta seleccionada = null;
        
        String titulo = listaPropuestas.getSelectedValue();
        
        for(propuesta p : ic.listarPropuestas()){
        if(p.getTitulo().equalsIgnoreCase(titulo)){
        seleccionada = p;
        break;
        }
        }
        
        textoNickname.setText(seleccionada.getProponente());
        textoEstado.setText(seleccionada.getEstadoActual().toString());
        textoRecaudado.setText(seleccionada.getRecaudado().toString());
                
    }//GEN-LAST:event_listaPropuestasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JList<String> ListaColaboradores;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTextField TextoApellido;
    private javax.swing.JTextField TextoNickname;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JTextField textoEstado;
    private javax.swing.JTextField textoNickname;
    private javax.swing.JTextField textoRecaudado;
    // End of variables declaration//GEN-END:variables
}
