/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import java.awt.CardLayout;

import logica.ictrl;

public class PanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuarios
     */
    private ictrl ic;
    
    private CardLayout c1;
    
    java.awt.CardLayout p1; //para volver atras
    javax.swing.JPanel PantallaGrandePrincipal; //para volver atras
    
    public PanelUsuarios(ictrl ic, java.awt.CardLayout p1, javax.swing.JPanel PantallaGrandePrincipal) {
        initComponents();
        
        this.ic = ic;
        
        c1 = new CardLayout();
        contenido.setLayout(c1);
        contenido.add(principal, "principal");
        c1.show(contenido, "principal");
        
        this.p1 = p1;
        this.PantallaGrandePrincipal = PantallaGrandePrincipal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonConsultaProponente = new javax.swing.JButton();
        BotonConsultaColaborador = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();
        principal = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonSeguir = new javax.swing.JButton();
        botonDejar = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 32, 56));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIOS");

        BotonConsultaProponente.setBackground(new java.awt.Color(119, 205, 215));
        BotonConsultaProponente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BotonConsultaProponente.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsultaProponente.setText("CONSULTA PERFIL PROPONENTE");
        BotonConsultaProponente.setBorder(null);
        BotonConsultaProponente.setBorderPainted(false);
        BotonConsultaProponente.setContentAreaFilled(false);
        BotonConsultaProponente.setOpaque(true);
        BotonConsultaProponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaProponenteActionPerformed(evt);
            }
        });

        BotonConsultaColaborador.setBackground(new java.awt.Color(119, 205, 215));
        BotonConsultaColaborador.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BotonConsultaColaborador.setForeground(new java.awt.Color(255, 255, 255));
        BotonConsultaColaborador.setText("CONSULTA PERFIL COLABORADOR");
        BotonConsultaColaborador.setBorder(null);
        BotonConsultaColaborador.setBorderPainted(false);
        BotonConsultaColaborador.setContentAreaFilled(false);
        BotonConsultaColaborador.setOpaque(true);
        BotonConsultaColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaColaboradorActionPerformed(evt);
            }
        });

        contenido.setPreferredSize(new java.awt.Dimension(1280, 900));

        principal.setBackground(new java.awt.Color(255, 240, 255));
        principal.setPreferredSize(new java.awt.Dimension(1343, 920));

        labelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo300.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(119, 205, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PANEL USUARIOS");

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(labelFoto))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(jLabel2)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        BotonVolver.setBackground(new java.awt.Color(119, 205, 215));
        BotonVolver.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BotonVolver.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolver.setText("ATRAS");
        BotonVolver.setBorderPainted(false);
        BotonVolver.setContentAreaFilled(false);
        BotonVolver.setOpaque(true);
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(119, 205, 215));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESAR USUARIO");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonSeguir.setBackground(new java.awt.Color(119, 205, 215));
        botonSeguir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonSeguir.setForeground(new java.awt.Color(255, 255, 255));
        botonSeguir.setText("SEGUIR USUARIO");
        botonSeguir.setBorder(null);
        botonSeguir.setBorderPainted(false);
        botonSeguir.setContentAreaFilled(false);
        botonSeguir.setOpaque(true);
        botonSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirActionPerformed(evt);
            }
        });

        botonDejar.setBackground(new java.awt.Color(119, 205, 215));
        botonDejar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonDejar.setForeground(new java.awt.Color(255, 255, 255));
        botonDejar.setText("DEJAR DE SEGUIR USUARIO");
        botonDejar.setBorder(null);
        botonDejar.setBorderPainted(false);
        botonDejar.setContentAreaFilled(false);
        botonDejar.setOpaque(true);
        botonDejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDejarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 113, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(BotonVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BotonConsultaProponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonConsultaColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonDejar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(BotonConsultaProponente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonConsultaColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDejar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultaColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaColaboradorActionPerformed
        // TODO add your handling code here:
        PanelConsultaColaborador cons = new PanelConsultaColaborador(ic);
        contenido.add(cons, "consulta2");
        c1.show(contenido, "consulta2");
    }//GEN-LAST:event_BotonConsultaColaboradorActionPerformed

    private void BotonConsultaProponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaProponenteActionPerformed
        // TODO add your handling code here:
        //cargar el panel PanelConsultaProponente en el contenido.
        PanelConsultaProponente cons = new PanelConsultaProponente(ic);
        contenido.add(cons, "consulta");
        c1.show(contenido, "consulta");
    }//GEN-LAST:event_BotonConsultaProponenteActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        p1.show(PantallaGrandePrincipal, "principal");
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelAltaUsuario p1 = new PanelAltaUsuario(ic, contenido); //decido pasarle contenido para de alla poder usarlo y limpiarlo
        contenido.add(p1, "altaUsuario");
        c1.show(contenido, "altaUsuario");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirActionPerformed
        // TODO add your handling code here:
        PanelSeguidos panelSeguidos = new PanelSeguidos(ic, contenido);
        contenido.add(panelSeguidos, "seguir");
        c1.show(contenido, "seguir");
    }//GEN-LAST:event_botonSeguirActionPerformed

    private void botonDejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDejarActionPerformed
        // TODO add your handling code here:
        PanelDejarSeguir panelDejar = new PanelDejarSeguir(ic, contenido);
        contenido.add(panelDejar, "dejar");
        c1.show(contenido, "dejar");
    }//GEN-LAST:event_botonDejarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultaColaborador;
    private javax.swing.JButton BotonConsultaProponente;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JButton botonDejar;
    private javax.swing.JButton botonSeguir;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
