/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;

import javax.swing.DefaultListModel;

import logica.categoria;

import java.util.List;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;

public class PanelIngresoCategoria extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresoCategoria
     */
    
    private ictrl ic;
    
    DefaultListModel<String> modelo = new DefaultListModel();
    
    public PanelIngresoCategoria(ictrl ic) {
        initComponents();
        this.ic = ic;  
    
    PanelSubCat.setVisible(false);
 
    //cargar el JTREE
    
    //traer categorias una vez sola
    List<categoria> cats = ic.listarCategoria();
    
    //cargo una vez la raiz
    if(cats.isEmpty()){
    ic.altaCategoria("Categoria");
    }

    // crear un nodo por categoria.
    Map<Integer, DefaultMutableTreeNode> nodos = new HashMap<>();
    for (categoria c : cats) {
        nodos.put(c.getId(), new DefaultMutableTreeNode(c));
    }

    //Elegir raiz: si existe una unica llamada "Categoría" y padre == null, usamos esa.
    //    Si no, creamos una raiz "Categorias".
    categoria raizCat = null;
    for (categoria c : cats) {
        if (c.getPadre() == null && "Categoria".equalsIgnoreCase(c.getNombre())) {
            raizCat = c;
            break;
        }
    }
    DefaultMutableTreeNode root = (raizCat != null) ? nodos.get(raizCat.getId()) : new DefaultMutableTreeNode("Categorías");

    //Armar la jerarquia
    for (categoria c : cats) {
        DefaultMutableTreeNode nodo = nodos.get(c.getId());
        if (nodo == null) continue;

        if (raizCat != null && c.getId() == raizCat.getId()) continue; // ya es root

        DefaultMutableTreeNode padreNodo = null;
        categoria p = c.getPadre();
        if (p != null) {
            padreNodo = nodos.get(p.getId());
        }

        if (padreNodo == null) {
            // sin padre conocido: colgar de la raiz seleccionada
            root.add(nodo);
        } else if (padreNodo != nodo) {
            padreNodo.add(nodo);
        }
    }

    //Setear modelo
    DefaultTreeModel model = new DefaultTreeModel(root);
    ArbolCategorias.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgrupadorBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BotonIngreso = new javax.swing.JButton();
        categoria = new javax.swing.JRadioButton();
        subcategoria = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        PanelSubCat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextoPadre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArbolCategorias = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("INGRESAR CATEGORIA");

        BotonIngreso.setBackground(new java.awt.Color(16, 32, 56));
        BotonIngreso.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonIngreso.setForeground(new java.awt.Color(255, 255, 255));
        BotonIngreso.setText("INGRESAR");
        BotonIngreso.setBorderPainted(false);
        BotonIngreso.setContentAreaFilled(false);
        BotonIngreso.setOpaque(true);
        BotonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresoActionPerformed(evt);
            }
        });

        categoria.setBackground(new java.awt.Color(255, 240, 255));
        AgrupadorBotones.add(categoria);
        categoria.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        categoria.setForeground(new java.awt.Color(16, 32, 56));
        categoria.setText("Categoria");
        categoria.setContentAreaFilled(false);
        categoria.setOpaque(true);
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaMouseClicked(evt);
            }
        });

        subcategoria.setBackground(new java.awt.Color(255, 240, 255));
        AgrupadorBotones.add(subcategoria);
        subcategoria.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        subcategoria.setForeground(new java.awt.Color(16, 32, 56));
        subcategoria.setText("Sub Categoria");
        subcategoria.setContentAreaFilled(false);
        subcategoria.setOpaque(true);
        subcategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subcategoriaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("INGRESA CATEGORIA");

        TextoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoNombre.setForeground(new java.awt.Color(16, 32, 56));
        TextoNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });

        PanelSubCat.setBackground(new java.awt.Color(255, 240, 255));

        jLabel3.setBackground(new java.awt.Color(119, 205, 215));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("INGRESA CATEGORIA PADRE");

        TextoPadre.setBackground(new java.awt.Color(255, 255, 255));
        TextoPadre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoPadre.setForeground(new java.awt.Color(16, 32, 56));
        TextoPadre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        javax.swing.GroupLayout PanelSubCatLayout = new javax.swing.GroupLayout(PanelSubCat);
        PanelSubCat.setLayout(PanelSubCatLayout);
        PanelSubCatLayout.setHorizontalGroup(
            PanelSubCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSubCatLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelSubCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(TextoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PanelSubCatLayout.setVerticalGroup(
            PanelSubCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSubCatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ArbolCategorias.setBackground(new java.awt.Color(255, 255, 255));
        ArbolCategorias.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ArbolCategorias.setForeground(new java.awt.Color(16, 32, 56));
        ArbolCategorias.setAutoscrolls(true);
        jScrollPane2.setViewportView(ArbolCategorias);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("CATEGORIAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(categoria)
                                .addGap(18, 18, 18)
                                .addComponent(subcategoria))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(PanelSubCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(BotonIngreso)))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoria)
                            .addComponent(subcategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelSubCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonIngreso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void BotonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresoActionPerformed
        // TODO add your handling code here:
        String nombre = TextoNombre.getText();
        
        //nuevo, verificar existencia.
        for(categoria c : ic.listarCategoria()){
        if(c.getNombre().equalsIgnoreCase(nombre)){
            JOptionPane.showMessageDialog(this, "Categoria existente.", "Datos existentes", JOptionPane.WARNING_MESSAGE);
        return;
        }
        }
        
        boolean esCategoria = categoria.isSelected();
        boolean esSub = subcategoria.isSelected();
        if(esCategoria){
        ic.altaCategoria(nombre);
        }
        if(esSub){
        String padre = TextoPadre.getText();
        boolean encontro = false;
        //buscar q exista el padre.
        for(categoria c : ic.listarCategoria()){
        if(c.getNombre().equalsIgnoreCase(padre)){
        ic.altaSubCategoria(nombre, padre);
        encontro = true;
        }
        }
        if(encontro == false){
        JOptionPane.showMessageDialog(this, "No existe la categoria padre.", "Datos inexistentes", JOptionPane.WARNING_MESSAGE);
        return;
        }
        }
        
        JOptionPane.showMessageDialog(this, "Categoria ingresada con exito.", "Operacion exitosa", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_BotonIngresoActionPerformed

    private void subcategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subcategoriaMouseClicked
        // TODO add your handling code here:
        //mostrar para que ponga el padre
        PanelSubCat.setVisible(true);
    }//GEN-LAST:event_subcategoriaMouseClicked

    private void categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseClicked
        // TODO add your handling code here:
        PanelSubCat.setVisible(false);
    }//GEN-LAST:event_categoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AgrupadorBotones;
    private javax.swing.JTree ArbolCategorias;
    private javax.swing.JButton BotonIngreso;
    private javax.swing.JPanel PanelSubCat;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoPadre;
    private javax.swing.JRadioButton categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton subcategoria;
    // End of variables declaration//GEN-END:variables
}
