/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;

import logica.propuesta;

import javax.swing.DefaultListModel;

public class PanelConsulta extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsulta
     */
    
    ictrl ic;
    
    private javax.swing.JPanel contenido;
    private java.awt.CardLayout c1;
    
    DefaultListModel modelo = new DefaultListModel();
    
    public PanelConsulta(ictrl ic, javax.swing.JPanel contenido, java.awt.CardLayout c1) {
        initComponents();
        
        this.ic = ic;
        this.contenido = contenido;
        this.c1 = c1;
        
        listaPropuestas.setModel(modelo);
        for(propuesta p : ic.listarPropuestas()){
        modelo.addElement("Titulo: " + p.getTitulo());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        textoProponente = new javax.swing.JTextField();
        textoTitulo = new javax.swing.JTextField();
        textoDescripcion = new javax.swing.JTextField();
        textoTipo = new javax.swing.JTextField();
        textoLugar = new javax.swing.JTextField();
        textoFecha = new javax.swing.JTextField();
        textoPrecio = new javax.swing.JTextField();
        textoMonto = new javax.swing.JTextField();
        labelImagen = new javax.swing.JLabel();
        textoEstado = new javax.swing.JTextField();
        textoRecaudado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("PROPUESTAS");

        listaPropuestas.setBackground(new java.awt.Color(255, 255, 255));
        listaPropuestas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaPropuestas.setForeground(new java.awt.Color(16, 32, 56));
        listaPropuestas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPropuestas);

        jPanel1.setBackground(new java.awt.Color(255, 240, 255));

        textoProponente.setEditable(false);
        textoProponente.setBackground(new java.awt.Color(255, 255, 255));
        textoProponente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoProponente.setForeground(new java.awt.Color(16, 32, 56));
        textoProponente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoTitulo.setEditable(false);
        textoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        textoTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(16, 32, 56));
        textoTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });

        textoDescripcion.setEditable(false);
        textoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        textoDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoDescripcion.setForeground(new java.awt.Color(16, 32, 56));
        textoDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoTipo.setEditable(false);
        textoTipo.setBackground(new java.awt.Color(255, 255, 255));
        textoTipo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoTipo.setForeground(new java.awt.Color(16, 32, 56));
        textoTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoLugar.setEditable(false);
        textoLugar.setBackground(new java.awt.Color(255, 255, 255));
        textoLugar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoLugar.setForeground(new java.awt.Color(16, 32, 56));
        textoLugar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoLugarActionPerformed(evt);
            }
        });

        textoFecha.setEditable(false);
        textoFecha.setBackground(new java.awt.Color(255, 255, 255));
        textoFecha.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoFecha.setForeground(new java.awt.Color(16, 32, 56));
        textoFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoPrecio.setEditable(false);
        textoPrecio.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoPrecio.setForeground(new java.awt.Color(16, 32, 56));
        textoPrecio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoMonto.setEditable(false);
        textoMonto.setBackground(new java.awt.Color(255, 255, 255));
        textoMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoMonto.setForeground(new java.awt.Color(16, 32, 56));
        textoMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoEstado.setEditable(false);
        textoEstado.setBackground(new java.awt.Color(255, 255, 255));
        textoEstado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoEstado.setForeground(new java.awt.Color(16, 32, 56));
        textoEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstadoActionPerformed(evt);
            }
        });

        textoRecaudado.setEditable(false);
        textoRecaudado.setBackground(new java.awt.Color(255, 255, 255));
        textoRecaudado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoRecaudado.setForeground(new java.awt.Color(16, 32, 56));
        textoRecaudado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoRecaudado)
                            .addComponent(textoFecha)
                            .addComponent(textoPrecio)
                            .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoProponente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoProponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("CONSULTA PROPUESTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaPropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropuestasMouseClicked
        // TODO add your handling code here:
        
        int i = listaPropuestas.getSelectedIndex();
        propuesta prop = ic.listarPropuestas().get(i);
        textoDescripcion.setText(prop.getDescripcion());
        textoProponente.setText(prop.getProponente());
        textoTitulo.setText(prop.getTitulo());
        textoTipo.setText(prop.getTipo());
        textoLugar.setText(prop.getLugar());
        textoFecha.setText(prop.getFecha().toString());
        textoPrecio.setText(prop.getEntrada().toString());
        textoMonto.setText(prop.getMonto().toString());
        
        //mostrar su imagen tamb
        labelImagen.setIcon(prop.bytesAIcon());
        
        //el estado
        textoEstado.setText(prop.getEstadoActual().toString());
        
        //nickname de los colaboradores.
        
        
        //monto recaudado hasta el momento
        textoRecaudado.setText(prop.getRecaudado().toString());
        
    }//GEN-LAST:event_listaPropuestasMouseClicked

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTituloActionPerformed

    private void textoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstadoActionPerformed

    private void textoLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoLugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JTextField textoDescripcion;
    private javax.swing.JTextField textoEstado;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoLugar;
    private javax.swing.JTextField textoMonto;
    private javax.swing.JTextField textoPrecio;
    private javax.swing.JTextField textoProponente;
    private javax.swing.JTextField textoRecaudado;
    private javax.swing.JTextField textoTipo;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables
}
