/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;

import logica.propuesta;

import logica.colaborador;
import logica.colaboracion;

import logica.proponente;

import javax.swing.DefaultListModel;

//para pasar la fecha q mostraba en ingles a formato mas lindo y espanol.
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;

public class PanelColaborar extends javax.swing.JPanel {

    /**
     * Creates new form PanelColaborar
     */
    
    ictrl ic;
    
    DefaultListModel modelo = new DefaultListModel();
    DefaultListModel modelo2 = new DefaultListModel();
    
    proponente proponente;
    propuesta prop;
    propuesta propuesta;
    colaborador colaborador;
    float monto;
    String retorno;
    
    String boton;
    
    public PanelColaborar(ictrl ic) {
        initComponents();
        
        this.ic = ic;
        
        listaPropuestas.setModel(modelo);
        for(propuesta p : ic.listarPropuestas()){
        modelo.addElement(p.getTitulo());
        }
        
        listaColaboradores.setModel(modelo2);
        for(colaborador c : ic.listarColaboradores()){
        modelo2.addElement(c.getNickname());
        }
        
        panelColabora.setVisible(false);
        
        botonEntrada.setVisible(false);
        botonPorcentaje.setVisible(false);
        botonAmbas.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textoProponente = new javax.swing.JTextField();
        textoTitulo = new javax.swing.JTextField();
        textoDescripcion = new javax.swing.JTextField();
        textoTipo = new javax.swing.JTextField();
        textoLugar = new javax.swing.JTextField();
        textoFecha = new javax.swing.JTextField();
        textoPrecio = new javax.swing.JTextField();
        textoMonto = new javax.swing.JTextField();
        labelImagen = new javax.swing.JLabel();
        textoEstado = new javax.swing.JTextField();
        textoRecaudado = new javax.swing.JTextField();
        botonColaborar = new javax.swing.JButton();
        panelColabora = new javax.swing.JPanel();
        textoMontoColaborador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonEntrada = new javax.swing.JRadioButton();
        botonPorcentaje = new javax.swing.JRadioButton();
        botonIngresar = new javax.swing.JButton();
        botonAmbas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaColaboradores = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        listaPropuestas.setBackground(new java.awt.Color(255, 255, 255));
        listaPropuestas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaPropuestas.setForeground(new java.awt.Color(16, 32, 56));
        listaPropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPropuestas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("PROPUESTAS");

        jPanel1.setBackground(new java.awt.Color(255, 240, 255));

        textoProponente.setEditable(false);
        textoProponente.setBackground(new java.awt.Color(255, 255, 255));
        textoProponente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoProponente.setForeground(new java.awt.Color(16, 32, 56));
        textoProponente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoTitulo.setEditable(false);
        textoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        textoTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(16, 32, 56));
        textoTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });

        textoDescripcion.setEditable(false);
        textoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        textoDescripcion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoDescripcion.setForeground(new java.awt.Color(16, 32, 56));
        textoDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoTipo.setEditable(false);
        textoTipo.setBackground(new java.awt.Color(255, 255, 255));
        textoTipo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoTipo.setForeground(new java.awt.Color(16, 32, 56));
        textoTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoLugar.setEditable(false);
        textoLugar.setBackground(new java.awt.Color(255, 255, 255));
        textoLugar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoLugar.setForeground(new java.awt.Color(16, 32, 56));
        textoLugar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoFecha.setEditable(false);
        textoFecha.setBackground(new java.awt.Color(255, 255, 255));
        textoFecha.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoFecha.setForeground(new java.awt.Color(16, 32, 56));
        textoFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoPrecio.setEditable(false);
        textoPrecio.setBackground(new java.awt.Color(255, 255, 255));
        textoPrecio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoPrecio.setForeground(new java.awt.Color(16, 32, 56));
        textoPrecio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoMonto.setEditable(false);
        textoMonto.setBackground(new java.awt.Color(255, 255, 255));
        textoMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoMonto.setForeground(new java.awt.Color(16, 32, 56));
        textoMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoEstado.setEditable(false);
        textoEstado.setBackground(new java.awt.Color(255, 255, 255));
        textoEstado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoEstado.setForeground(new java.awt.Color(16, 32, 56));
        textoEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoRecaudado.setEditable(false);
        textoRecaudado.setBackground(new java.awt.Color(255, 255, 255));
        textoRecaudado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoRecaudado.setForeground(new java.awt.Color(16, 32, 56));
        textoRecaudado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoRecaudado, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(textoEstado)
                    .addComponent(textoProponente)
                    .addComponent(textoTitulo)
                    .addComponent(textoDescripcion)
                    .addComponent(textoTipo)
                    .addComponent(textoLugar)
                    .addComponent(textoFecha)
                    .addComponent(textoPrecio)
                    .addComponent(textoMonto))
                .addGap(48, 48, 48)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoProponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        botonColaborar.setBackground(new java.awt.Color(16, 32, 56));
        botonColaborar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonColaborar.setForeground(new java.awt.Color(255, 255, 255));
        botonColaborar.setText("COLABORAR");
        botonColaborar.setBorderPainted(false);
        botonColaborar.setContentAreaFilled(false);
        botonColaborar.setOpaque(true);
        botonColaborar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColaborarActionPerformed(evt);
            }
        });

        panelColabora.setBackground(new java.awt.Color(255, 255, 255));
        panelColabora.setOpaque(false);

        textoMontoColaborador.setBackground(new java.awt.Color(255, 255, 255));
        textoMontoColaborador.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoMontoColaborador.setForeground(new java.awt.Color(16, 32, 56));
        textoMontoColaborador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("Monto");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("Retorno");

        botonEntrada.setBackground(new java.awt.Color(255, 240, 255));
        buttonGroup1.add(botonEntrada);
        botonEntrada.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonEntrada.setForeground(new java.awt.Color(16, 32, 56));
        botonEntrada.setText("ENTRADA GRATIS");
        botonEntrada.setBorder(null);

        botonPorcentaje.setBackground(new java.awt.Color(255, 240, 255));
        buttonGroup1.add(botonPorcentaje);
        botonPorcentaje.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonPorcentaje.setForeground(new java.awt.Color(16, 32, 56));
        botonPorcentaje.setText("PORCENTAJE");
        botonPorcentaje.setBorder(null);

        botonIngresar.setBackground(new java.awt.Color(16, 32, 56));
        botonIngresar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("INGRESAR COLABORACION");
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setOpaque(true);
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonAmbas.setBackground(new java.awt.Color(255, 240, 255));
        buttonGroup1.add(botonAmbas);
        botonAmbas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonAmbas.setForeground(new java.awt.Color(16, 32, 56));
        botonAmbas.setText("AMBAS");
        botonAmbas.setBorder(null);

        javax.swing.GroupLayout panelColaboraLayout = new javax.swing.GroupLayout(panelColabora);
        panelColabora.setLayout(panelColaboraLayout);
        panelColaboraLayout.setHorizontalGroup(
            panelColaboraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColaboraLayout.createSequentialGroup()
                .addGroup(panelColaboraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColaboraLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(panelColaboraLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelColaboraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelColaboraLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addComponent(textoMontoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelColaboraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonPorcentaje)
                        .addGap(18, 18, 18)
                        .addComponent(botonAmbas))
                    .addGroup(panelColaboraLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botonIngresar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelColaboraLayout.setVerticalGroup(
            panelColaboraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColaboraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(textoMontoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelColaboraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEntrada)
                    .addComponent(botonPorcentaje)
                    .addComponent(botonAmbas))
                .addGap(26, 26, 26)
                .addComponent(botonIngresar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("COLABORADORES");

        listaColaboradores.setBackground(new java.awt.Color(255, 255, 255));
        listaColaboradores.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaColaboradores.setForeground(new java.awt.Color(16, 32, 56));
        jScrollPane2.setViewportView(listaColaboradores);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 32, 56));
        jLabel5.setText("COLABORAR A PROPUESTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botonColaborar)
                                        .addGap(118, 118, 118))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(79, 79, 79)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelColabora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(botonColaborar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(panelColabora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTituloActionPerformed

    private void listaPropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropuestasMouseClicked
        // TODO add your handling code here:
        
       //int i = listaPropuestas.getSelectedIndex();
       //propuesta prop = ic.listarPropuestas().get(i);
       
       propuesta seleccionada = null;
       String titulo = listaPropuestas.getSelectedValue();
       for(propuesta p : ic.listarPropuestas()){
       if(p.getTitulo().equalsIgnoreCase(titulo)){
       seleccionada = p;
       break;
       }
       }

       this.prop = seleccionada;
       this.propuesta = seleccionada;
       
        textoDescripcion.setText(prop.getDescripcion());
        textoProponente.setText(prop.getProponente());
        textoTitulo.setText(prop.getTitulo());
        textoTipo.setText(prop.getTipo());
        textoLugar.setText(prop.getLugar());
        
        Locale esUY = new Locale("es", "UY");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm", esUY);
        sdf.setTimeZone(TimeZone.getTimeZone("America/Montevideo"));
        
        textoFecha.setText(sdf.format(prop.getFecha()));
        textoPrecio.setText(prop.getEntrada().toString());
        textoMonto.setText(prop.getMonto().toString());
        
        //mostrar su imagen tamb
        labelImagen.setIcon(prop.bytesAIcon());
        
        //el estado
        textoEstado.setText(prop.getEstadoActual().toString());
        
        //monto recaudado hasta el momento
        textoRecaudado.setText(prop.getRecaudado().toString());
        
        String nom = prop.getProponente();
        
        for(proponente p : ic.listarProponentes()){
         if(p.getNickname().equalsIgnoreCase(nom)){
         this.proponente = p;
         break;
        }
      }
        
        //deberia mostrar solo los botones d tipo retorno q la propuesta tenga.
        String tipoRetorno = prop.getTipoRetorno();
        if(tipoRetorno.equalsIgnoreCase("Entrada")){
        this.boton = "Entrada";
        }else if(tipoRetorno.equalsIgnoreCase("Porcentaje")){
        this.boton = "Porcentaje";
        }else if(tipoRetorno.equalsIgnoreCase("Ambas")){
        this.boton = "Ambas";
        }
        
    }//GEN-LAST:event_listaPropuestasMouseClicked

    private void botonColaborarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColaborarActionPerformed
        // TODO add your handling code here:

        panelColabora.setVisible(true);
        
                switch(boton){
            case "Entrada" : 
                botonEntrada.setVisible(true);
                break;
                
            case "Porcentaje" : 
                botonPorcentaje.setVisible(true);
                break;
                
            case "Ambas" : 
                botonAmbas.setVisible(true);
                break;
        }
        
    }//GEN-LAST:event_botonColaborarActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        
        String m = textoMontoColaborador.getText();
        if(m == null || m.trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un monto.", "Faltan datos", javax.swing.JOptionPane.WARNING_MESSAGE);
        textoMonto.requestFocus();
        return;
        }
        
        String s = m.trim().replace("\u00A0", "")
                           .replace(".", "")
                           .replace(',', '.');
        
        monto = Float.parseFloat(s);
        
        if(botonEntrada.isSelected()){
        retorno = "Entrada";
        }
        if(botonPorcentaje.isSelected()){
        retorno = "Porcentaje";
        }
        if(botonAmbas.isSelected()){
        retorno = "Ambas";
        }
        
        String texto = listaColaboradores.getSelectedValue();
        this.colaborador = null;
        for(colaborador c : ic.listarColaboradores()){
        if(c.getNickname().equalsIgnoreCase(texto)){
        this.colaborador = c;
        break;
        }
        }
        
        if (this.colaborador == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontro el colaborador seleccionado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        //verificar q ha retorno seleccionado.
             switch(boton){
            case "Entrada" : 
                if(botonEntrada.isSelected()){
                break;
                }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona tipo retorno", "Faltan datos", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
                }
                
                
            case "Porcentaje" : 
                if(botonPorcentaje.isSelected()){
                break;
                }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona tipo retorno", "Faltan datos", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
                }
               
                
            case "Ambas" : 
                if(botonAmbas.isSelected()){
                break;
                }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona tipo retorno", "Faltan datos", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
                }
               
        }
        
             //verificar q no haya colaborado ya con esa propuesta.
             for(colaboracion c : ic.listarColaboraciones()){
             if(c.getPropuesta().getTitulo().equalsIgnoreCase(propuesta.getTitulo()) && c.getColaborador().getNickname().equalsIgnoreCase(colaborador.getNickname())){
             javax.swing.JOptionPane.showMessageDialog(this, "Este usuario ya colaboro con la propuesta.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             return;
             }
             }
             
      try{
        ic.altaColaboracion(this.colaborador, this.propuesta, monto, retorno);
        javax.swing.JOptionPane.showMessageDialog(this, "Colaboracion registrada.");
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar la colaboracion: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_botonIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonAmbas;
    private javax.swing.JButton botonColaborar;
    private javax.swing.JRadioButton botonEntrada;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JRadioButton botonPorcentaje;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JList<String> listaColaboradores;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JPanel panelColabora;
    private javax.swing.JTextField textoDescripcion;
    private javax.swing.JTextField textoEstado;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoLugar;
    private javax.swing.JTextField textoMonto;
    private javax.swing.JTextField textoMontoColaborador;
    private javax.swing.JTextField textoPrecio;
    private javax.swing.JTextField textoProponente;
    private javax.swing.JTextField textoRecaudado;
    private javax.swing.JTextField textoTipo;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables
}
