/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;

import logica.usuario;

import logica.colaborador;

import logica.colaboracion;

import javax.swing.DefaultListModel;

//para pasar la fecha q mostraba en ingles a formato mas lindo y espanol.
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;

public class PanelConsultaColab extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultaColab
     */
    
    ictrl ic;
    
    DefaultListModel modelo = new DefaultListModel();
    
    DefaultListModel modelo2 = new DefaultListModel();
    
    colaborador colaborador;
    
    public PanelConsultaColab(ictrl ic) {
        initComponents();
        
        this.ic = ic;
        
        listaColaboradores.setModel(modelo);
        for(colaborador c : ic.listarColaboradores()){
        modelo.addElement(c.getNickname());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaColaboradores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaColab = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textoFechaHora = new javax.swing.JTextField();
        textoMonto = new javax.swing.JTextField();
        textoRetorno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("COLABORADORES");

        listaColaboradores.setBackground(new java.awt.Color(255, 255, 255));
        listaColaboradores.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaColaboradores.setForeground(new java.awt.Color(16, 32, 56));
        listaColaboradores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaColaboradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaColaboradores);

        listaColab.setBackground(new java.awt.Color(255, 255, 255));
        listaColab.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaColab.setForeground(new java.awt.Color(16, 32, 56));
        listaColab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaColabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaColab);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("COLABORACIONES");

        jPanel1.setBackground(new java.awt.Color(255, 240, 255));

        textoFechaHora.setEditable(false);
        textoFechaHora.setBackground(new java.awt.Color(255, 255, 255));
        textoFechaHora.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoFechaHora.setForeground(new java.awt.Color(16, 32, 56));
        textoFechaHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoMonto.setEditable(false);
        textoMonto.setBackground(new java.awt.Color(255, 255, 255));
        textoMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoMonto.setForeground(new java.awt.Color(16, 32, 56));
        textoMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        textoRetorno.setEditable(false);
        textoRetorno.setBackground(new java.awt.Color(255, 255, 255));
        textoRetorno.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoRetorno.setForeground(new java.awt.Color(16, 32, 56));
        textoRetorno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoFechaHora)
                    .addComponent(textoMonto)
                    .addComponent(textoRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textoFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("CONSULTA COLABORACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaColaboradoresMouseClicked
        // TODO add your handling code here:
        
         modelo2.clear();
         listaColab.setModel(modelo2);
        
        //guardo el colaborador.
        String texto = listaColaboradores.getSelectedValue();
        if(texto == null) return;
        this.colaborador = null;
        for(colaborador c : ic.listarColaboradores()){
        if(c != null && c.getNickname().equalsIgnoreCase(texto)){
        this.colaborador = c;
        break;
        }
        }
        
        if(this.colaborador == null) return;
        
        //listar las colaboraciones. si tiene.
       if(ic.listarColaboraciones() == null) return;
       for(colaboracion co : ic.listarColaboraciones()){
        if(co == null) continue;
        if(co.getColaborador() == null) continue;
        if(co.getColaborador().getNickname().equalsIgnoreCase(colaborador.getNickname())){
        modelo2.addElement("Colaboracion: " + co.getPropuesta().getTitulo());
        }
       }

    }//GEN-LAST:event_listaColaboradoresMouseClicked

    private void listaColabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaColabMouseClicked
        // TODO add your handling code here:
        
        //mostrar info de la colab elejida
        int i = listaColab.getSelectedIndex();
        colaboracion c = ic.listarColaboraciones().get(i);
        
        Locale esUY = new Locale("es", "UY");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm", esUY);
        sdf.setTimeZone(TimeZone.getTimeZone("America/Montevideo"));
        
        //textoFechaHora.setText(c.getFecha().toString()); antes era asi.
        textoFechaHora.setText(sdf.format(c.getFecha()));
        textoMonto.setText(c.getMontoAportado().toString());
        textoRetorno.setText(c.getTipoRetorno());
        
    }//GEN-LAST:event_listaColabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaColab;
    private javax.swing.JList<String> listaColaboradores;
    private javax.swing.JTextField textoFechaHora;
    private javax.swing.JTextField textoMonto;
    private javax.swing.JTextField textoRetorno;
    // End of variables declaration//GEN-END:variables
}
