/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;

import logica.propuesta;

import javax.swing.DefaultListModel;

import java.util.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;

//para pasar la fecha q mostraba en ingles a formato mas lindo y espanol.
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;

public class PanelModifico extends javax.swing.JPanel {

    /**
     * Creates new form PanelModifico
     */
    
    ictrl ic;
    
    javax.swing.JPanel contenido;
    java.awt.CardLayout c1;
    
    DefaultListModel modelo = new DefaultListModel();
    DefaultListModel modelo2 = new DefaultListModel();
    
    propuesta propGuardada;
    String cambio;
    
    public PanelModifico(ictrl ic, javax.swing.JPanel contenido, java.awt.CardLayout c1) {
        initComponents();
        this.ic = ic;
        
        //guardo el card layout de contenido para volver a principal
        this.contenido = contenido;
        this.c1 = c1;
        
        listaProp.setModel(modelo);
        for(propuesta p : ic.listarPropuestas()){
        modelo.addElement("Titulo: " + p.getTitulo());
        }
        
        listaInfo.setModel(modelo2);
        
        panelOculto.setVisible(false);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProp = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaInfo = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        panelOculto = new javax.swing.JPanel();
        textoIngresado = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SpinnerDia = new javax.swing.JSpinner();
        SpinnerMes = new javax.swing.JSpinner();
        SpinnerAno = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("MODIFICAR PROPUESTA");

        listaProp.setBackground(new java.awt.Color(255, 255, 255));
        listaProp.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaProp.setForeground(new java.awt.Color(16, 32, 56));
        listaProp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaProp);

        listaInfo.setBackground(new java.awt.Color(255, 255, 255));
        listaInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaInfo.setForeground(new java.awt.Color(16, 32, 56));
        listaInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaInfo);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("PROPUESTAS");

        panelOculto.setBackground(new java.awt.Color(255, 255, 255));
        panelOculto.setOpaque(false);

        textoIngresado.setBackground(new java.awt.Color(255, 255, 255));
        textoIngresado.setForeground(new java.awt.Color(16, 32, 56));
        textoIngresado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIngresadoActionPerformed(evt);
            }
        });

        botonIngresar.setBackground(new java.awt.Color(16, 32, 56));
        botonIngresar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("INGRESAR");
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setOpaque(true);
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("INGRESE EL NUEVO VALOR");

        SpinnerDia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        SpinnerDia.setBorder(null);
        SpinnerDia.setOpaque(false);

        SpinnerMes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        SpinnerMes.setBorder(null);
        SpinnerMes.setOpaque(false);

        SpinnerAno.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SpinnerAno.setModel(new javax.swing.SpinnerNumberModel(2025, 2025, 2030, 1));
        SpinnerAno.setBorder(null);
        SpinnerAno.setOpaque(false);

        javax.swing.GroupLayout panelOcultoLayout = new javax.swing.GroupLayout(panelOculto);
        panelOculto.setLayout(panelOcultoLayout);
        panelOcultoLayout.setHorizontalGroup(
            panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOcultoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOcultoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOcultoLayout.createSequentialGroup()
                        .addComponent(botonIngresar)
                        .addGap(72, 72, 72)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panelOcultoLayout.setVerticalGroup(
            panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOcultoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonIngresar)
                .addGap(9, 9, 9))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("SELECCIONA LOS DATOS A MODIFICAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39)
                .addComponent(panelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaPropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropMouseClicked
        // TODO add your handling code here:

        propuesta prop = null;
        int i = listaProp.getSelectedIndex();
        if(i >= 0){
        prop = ic.listarPropuestas().get(i);
        }
        
        //deberia mostrar los datos del seleccionado en la listaInfo.
        listaInfo.setModel(modelo2);
        modelo2.addElement("Descripcion: " + prop.getDescripcion());
        modelo2.addElement("Tipo Espectaculo: " + prop.getTipo());
        modelo2.addElement("Lugar: " + prop.getLugar());
        
        Locale esUY = new Locale("es", "UY");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm", esUY);
        sdf.setTimeZone(TimeZone.getTimeZone("America/Montevideo"));
        
        modelo2.addElement("Fecha Realizacion: " + sdf.format(prop.getFecha()));
        modelo2.addElement("Precio Entrada: " + prop.getEntrada());
        modelo2.addElement("Monto Necesario: " + prop.getMonto());
        
        propGuardada = prop;
        
    }//GEN-LAST:event_listaPropMouseClicked

    private void listaInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaInfoMouseClicked
        // TODO add your handling code here:
        
        if(listaInfo.getSelectedValue().contains("Descripcion")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(true);
        SpinnerDia.setVisible(false);
        SpinnerMes.setVisible(false);
        SpinnerAno.setVisible(false);
        this.cambio = "desc";
        }
        if(listaInfo.getSelectedValue().contains("Tipo")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(true);
        SpinnerDia.setVisible(false);
        SpinnerMes.setVisible(false);
        SpinnerAno.setVisible(false);
        this.cambio = "tipo";
        }
        if(listaInfo.getSelectedValue().contains("Lugar")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(true);
        SpinnerDia.setVisible(false);
        SpinnerMes.setVisible(false);
        SpinnerAno.setVisible(false);
        this.cambio = "lugar";
        }
        if(listaInfo.getSelectedValue().contains("Fecha")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(false);
        SpinnerDia.setVisible(true);
        SpinnerMes.setVisible(true);
        SpinnerAno.setVisible(true);
        this.cambio = "fecha";
        }
        if(listaInfo.getSelectedValue().contains("Precio")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(true);
        SpinnerDia.setVisible(false);
        SpinnerMes.setVisible(false);
        SpinnerAno.setVisible(false);
        this.cambio = "precio";
        }
        if(listaInfo.getSelectedValue().contains("Monto")){
        panelOculto.setVisible(true);
        textoIngresado.setVisible(true);
        SpinnerDia.setVisible(false);
        SpinnerMes.setVisible(false);
        SpinnerAno.setVisible(false);
        this.cambio = "monto";
        }
        
    }//GEN-LAST:event_listaInfoMouseClicked

    private void textoIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIngresadoActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        
        if(this.cambio == "desc"){
        String nuevaDesc = textoIngresado.getText();
        propGuardada.setDescripcion(nuevaDesc);
        ic.modificoPropuesta(propGuardada);
        }
        if(this.cambio == "tipo"){
        String nuevoTipo = textoIngresado.getText();
        propGuardada.setTipo(nuevoTipo);
        ic.modificoPropuesta(propGuardada);
        }
        if(this.cambio == "lugar"){
        String nuevoLugar = textoIngresado.getText();
        propGuardada.setLugar(nuevoLugar);
        ic.modificoPropuesta(propGuardada);
        }
        if(this.cambio == "fecha"){
        int dia = (int) SpinnerDia.getValue();
        int mes = (int) SpinnerMes.getValue();
        int anio = (int) SpinnerAno.getValue();
        Calendar cal = Calendar.getInstance();
        cal.set(anio, mes - 1, dia);
        Date fecha = cal.getTime();
        propGuardada.setFecha(fecha);
        ic.modificoPropuesta(propGuardada);
        }
        if(this.cambio == "precio"){
        float nuevoPrecio = Float.parseFloat(textoIngresado.getText());
        propGuardada.setPrecio(nuevoPrecio);
        ic.modificoPropuesta(propGuardada);
        }
        if(this.cambio == "monto"){
        float nuevoMonto = Float.parseFloat(textoIngresado.getText());
        propGuardada.setMonto(nuevoMonto);
        ic.modificoPropuesta(propGuardada);
        }
        
        c1.show(contenido, "principal");
        
    }//GEN-LAST:event_botonIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerAno;
    private javax.swing.JSpinner SpinnerDia;
    private javax.swing.JSpinner SpinnerMes;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaInfo;
    private javax.swing.JList<String> listaProp;
    private javax.swing.JPanel panelOculto;
    private javax.swing.JTextField textoIngresado;
    // End of variables declaration//GEN-END:variables
}
