/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import java.util.ArrayList;
import logica.fabrica;
import logica.ictrl;

import java.awt.CardLayout; //para pasar como en paginas
import javax.swing.JOptionPane; //para ventanita de errores y exitos.

import logica.proponente;
import logica.colaborador;

//para imagen
import java.io.File;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import javax.swing.ImageIcon;
import javax.swing.Icon;

public class PanelAltaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelAltaUsuario
     */
    
    private ictrl ic;
    private byte[] imagenBytes = null;
    
    javax.swing.JPanel contenido;
            
    public PanelAltaUsuario(ictrl ic, javax.swing.JPanel contenido) {
        initComponents();
        this.ic = ic;
        this.contenido = contenido;
        Panelsito1.setVisible(false); //oculto el panelsito con lo del proponente.
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgrupadorBotones = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nickname = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        proponente = new javax.swing.JRadioButton();
        colaborador = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        seleccionarImagen = new javax.swing.JButton();
        Panelsito1 = new javax.swing.JPanel();
        txt_direccion1 = new javax.swing.JTextField();
        txt_biografia1 = new javax.swing.JTextField();
        txt_linkSitio1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        panelFoto = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("INGRESE LOS DATOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("Nickname");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 32, 56));
        jLabel5.setText("Apellido");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(16, 32, 56));
        jLabel6.setText("E-mail");

        txt_nickname.setBackground(new java.awt.Color(255, 255, 255));
        txt_nickname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_nickname.setForeground(new java.awt.Color(16, 32, 56));
        txt_nickname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        txt_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicknameActionPerformed(evt);
            }
        });

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(16, 32, 56));
        txt_nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        txt_apellido.setBackground(new java.awt.Color(255, 255, 255));
        txt_apellido.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(16, 32, 56));
        txt_apellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(16, 32, 56));
        txt_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        proponente.setBackground(new java.awt.Color(255, 240, 255));
        AgrupadorBotones.add(proponente);
        proponente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        proponente.setForeground(new java.awt.Color(16, 32, 56));
        proponente.setText("proponente");
        proponente.setContentAreaFilled(false);
        proponente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                proponenteStateChanged(evt);
            }
        });
        proponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proponenteMouseClicked(evt);
            }
        });
        proponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proponenteActionPerformed(evt);
            }
        });

        colaborador.setBackground(new java.awt.Color(255, 240, 255));
        AgrupadorBotones.add(colaborador);
        colaborador.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        colaborador.setForeground(new java.awt.Color(16, 32, 56));
        colaborador.setText("colaborador");
        colaborador.setContentAreaFilled(false);
        colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradorActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(16, 32, 56));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("cancelar");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        seleccionarImagen.setBackground(new java.awt.Color(16, 32, 56));
        seleccionarImagen.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        seleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        seleccionarImagen.setText("seleccionar imagen");
        seleccionarImagen.setBorderPainted(false);
        seleccionarImagen.setContentAreaFilled(false);
        seleccionarImagen.setOpaque(true);
        seleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarImagenActionPerformed(evt);
            }
        });

        Panelsito1.setOpaque(false);

        txt_direccion1.setBackground(new java.awt.Color(255, 255, 255));
        txt_direccion1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_direccion1.setForeground(new java.awt.Color(16, 32, 56));
        txt_direccion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        txt_biografia1.setBackground(new java.awt.Color(255, 255, 255));
        txt_biografia1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_biografia1.setForeground(new java.awt.Color(16, 32, 56));
        txt_biografia1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        txt_linkSitio1.setBackground(new java.awt.Color(255, 255, 255));
        txt_linkSitio1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_linkSitio1.setForeground(new java.awt.Color(16, 32, 56));
        txt_linkSitio1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(16, 32, 56));
        jLabel11.setText("Direccion");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(16, 32, 56));
        jLabel12.setText("Biografia");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(16, 32, 56));
        jLabel13.setText("Link Sitio");

        javax.swing.GroupLayout Panelsito1Layout = new javax.swing.GroupLayout(Panelsito1);
        Panelsito1.setLayout(Panelsito1Layout);
        Panelsito1Layout.setHorizontalGroup(
            Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panelsito1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_biografia1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(txt_linkSitio1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_direccion1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        Panelsito1Layout.setVerticalGroup(
            Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panelsito1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_direccion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_biografia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panelsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_linkSitio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12))
        );

        aceptar.setBackground(new java.awt.Color(16, 32, 56));
        aceptar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("aceptar");
        aceptar.setBorderPainted(false);
        aceptar.setContentAreaFilled(false);
        aceptar.setOpaque(true);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        panelFoto.setBackground(new java.awt.Color(255, 240, 255));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        labelFoto.setBackground(new java.awt.Color(255, 240, 255));
        labelFoto.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panelsito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(129, 129, 129)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre)
                            .addComponent(txt_nickname)
                            .addComponent(txt_apellido)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(proponente)
                                .addGap(67, 67, 67)
                                .addComponent(colaborador))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(seleccionarImagen))
                            .addComponent(txt_email))))
                .addGap(36, 36, 36)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(seleccionarImagen))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proponente)
                    .addComponent(colaborador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelsito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptar)
                    .addComponent(jButton2))
                .addGap(119, 119, 119))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("INGRESO USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String nickname;
        String nombre;
        String apellido;
        String email;
        nickname = txt_nickname.getText();
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        email = txt_email.getText();

        boolean esProponente = proponente.isSelected();
        boolean esColaborador = colaborador.isSelected();

        String direccion = null;
        String biografia = null;
        String linkSitio = null;

        if(nickname.isEmpty()){
            JOptionPane.showMessageDialog(this, "El nickname es obligatorio.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            txt_nickname.requestFocus();
            return;
        }
        if(nombre.isEmpty() || apellido.isEmpty() || email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Completa nombre, apellido y email.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!esProponente && !esColaborador){
            JOptionPane.showMessageDialog(this, "Selecciona si es proponente o colaborador.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(esProponente){
            
            //verificar q no existan los datos en la bd
            for(proponente p : ic.listarProponentes()){
            if(p.getNickname().equalsIgnoreCase(nickname)){
            JOptionPane.showMessageDialog(this, "Nickname ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(p.getEmail().equalsIgnoreCase(email)){
            JOptionPane.showMessageDialog(this, "Email ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            }
            
            for(colaborador c : ic.listarColaboradores()){
            if(c.getNickname().equalsIgnoreCase(nickname)){
            JOptionPane.showMessageDialog(this, "Nickname ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(c.getEmail().equalsIgnoreCase(email)){
            JOptionPane.showMessageDialog(this, "Email ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            }
            
            direccion = txt_direccion1.getText();
            biografia = txt_biografia1.getText();
            linkSitio = txt_linkSitio1.getText();

            if(direccion.isEmpty() || biografia.isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese los datos faltantes.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //altaProponente
            ic.altaPerfilProponente(nickname, nombre, apellido, email, imagenBytes, direccion, biografia, linkSitio);
        }

        if(esColaborador){
            
            //verificar q no existan los datos en la bd
            
            for(proponente p : ic.listarProponentes()){
            if(p.getNickname().equalsIgnoreCase(nickname)){
            JOptionPane.showMessageDialog(this, "Nickname ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(p.getEmail().equalsIgnoreCase(email)){
            JOptionPane.showMessageDialog(this, "Email ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            }
            
            for(colaborador c : ic.listarColaboradores()){
            if(c.getNickname().equalsIgnoreCase(nickname)){
            JOptionPane.showMessageDialog(this, "Nickname ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            if(c.getEmail().equalsIgnoreCase(email)){
            JOptionPane.showMessageDialog(this, "Email ya existe.", "Informacion ya existente", JOptionPane.WARNING_MESSAGE);
            return;
            }
            }
            
            //altaColaborador...
            ic.altaPerfilColaborador(nickname, nombre, apellido, email, imagenBytes);
        }
        
        JOptionPane.showMessageDialog(this, "Usuario ingresado con exito.", "Operacion exitosa", JOptionPane.WARNING_MESSAGE);

        //volver al principal
        CardLayout c1 = (CardLayout) contenido.getLayout();
        c1.show(contenido, "principal");

    }//GEN-LAST:event_aceptarActionPerformed

    private void seleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarImagenActionPerformed
        // TODO add your handling code here:

        //deberia abrir una ventana con el file chooser
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Seleccionar imagen.");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagenes (JPG, PNG, JPEG)", "jpg", "jpeg", "png"));
        chooser.showOpenDialog(jPanel1);

        java.io.File f = chooser.getSelectedFile();
        if(f == null || !f.exists()){
            javax.swing.JOptionPane.showMessageDialog(this, "No se selecciono un archivo valido.", "Atencion", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try{
            java.awt.image.BufferedImage imagen = javax.imageio.ImageIO.read(f);
            if(imagen == null){
                javax.swing.JOptionPane.showMessageDialog(this, "El archivo no es una imagen valida.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            //tamano de destino
            int boxW = labelFoto.getWidth();
            int boxH = labelFoto.getHeight();
            if (boxW <= 0 || boxH <= 0) { boxW = 160; boxH = 160; }

            //mantener proporciones
            int w = imagen.getWidth(), h = imagen.getHeight();
            double scale = Math.min((double) boxW / w, (double) boxH / h);
            int nw = Math.max(1, (int) Math.round(w * scale));
            int nh = Math.max(1, (int) Math.round(h * scale));

            // escalar con calidad
            java.awt.image.BufferedImage scaled = new java.awt.image.BufferedImage(nw, nh, java.awt.image.BufferedImage.TYPE_INT_ARGB);
            java.awt.Graphics2D g2 = scaled.createGraphics();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g2.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING,      java.awt.RenderingHints.VALUE_RENDER_QUALITY);
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,   java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.drawImage(imagen, 0, 0, nw, nh, null);
            g2.dispose();

            //mostrar en el JLabel
            labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            labelFoto.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            labelFoto.setIcon(new javax.swing.ImageIcon(scaled));

            panelFoto.setVisible(true);
            panelFoto.revalidate();
            panelFoto.repaint();;

            java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
            javax.imageio.ImageIO.write(scaled, "png", baos);
            baos.flush();
            imagenBytes = baos.toByteArray();
            baos.close();

        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen.\n" + e.getMessage(),"Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_seleccionarImagenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void proponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proponenteActionPerformed
        // TODO add your handling code here:
        Panelsito1.setVisible(proponente.isSelected());
    }//GEN-LAST:event_proponenteActionPerformed

    private void proponenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proponenteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_proponenteMouseClicked

    private void proponenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_proponenteStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_proponenteStateChanged

    private void txt_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicknameActionPerformed

    private void colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradorActionPerformed
        // TODO add your handling code here:
        Panelsito1.setVisible(false);
    }//GEN-LAST:event_colaboradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AgrupadorBotones;
    private javax.swing.JPanel Panelsito1;
    private javax.swing.JButton aceptar;
    private javax.swing.JRadioButton colaborador;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JPanel panelFoto;
    private javax.swing.JRadioButton proponente;
    private javax.swing.JButton seleccionarImagen;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_biografia1;
    private javax.swing.JTextField txt_direccion1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_linkSitio1;
    private javax.swing.JTextField txt_nickname;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
