/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;
import logica.proponente;
import logica.propuesta;
import logica.colaboracion;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class PanelConsultaProponente extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultaProponente
     */
    
    private ictrl ic;
    
    List lista = null;
    DefaultListModel<String> modelo = new DefaultListModel<>();
    
    DefaultListModel<String> modeloPropuesta = new DefaultListModel<>();
    
    DefaultListModel<String> modeloUsuarios = new DefaultListModel<>();
    
    public PanelConsultaProponente(ictrl ic) {
        initComponents();
        this.ic = ic;
        ListaProponentes.setModel(modelo);
        for(proponente p : ic.listarProponentes()){
        modelo.addElement("Nickname: " + p.getNickname() + " | Nombre: " + p.getNombre() + " | Apellido: " + p.getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProponentes = new javax.swing.JList<>();
        PanelDatos = new javax.swing.JPanel();
        TextoNickname = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoApellido = new javax.swing.JTextField();
        labelFoto = new javax.swing.JLabel();
        TextoWeb = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaBiografia = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        TextoDesc = new javax.swing.JTextField();
        TextoTipo = new javax.swing.JTextField();
        TextoEntrada = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        textoEstado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoRecaudado = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("CONSULTA PROPONENTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("LISTA DE PROPONENTES");

        ListaProponentes.setBackground(new java.awt.Color(255, 255, 255));
        ListaProponentes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaProponentes.setForeground(new java.awt.Color(16, 32, 56));
        ListaProponentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaProponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaProponentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaProponentes);

        PanelDatos.setOpaque(false);

        TextoNickname.setEditable(false);
        TextoNickname.setBackground(new java.awt.Color(255, 255, 255));
        TextoNickname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoNickname.setForeground(new java.awt.Color(16, 32, 56));
        TextoNickname.setToolTipText("");
        TextoNickname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNicknameActionPerformed(evt);
            }
        });

        TextoNombre.setEditable(false);
        TextoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoNombre.setForeground(new java.awt.Color(16, 32, 56));
        TextoNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });

        TextoApellido.setEditable(false);
        TextoApellido.setBackground(new java.awt.Color(255, 255, 255));
        TextoApellido.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoApellido.setForeground(new java.awt.Color(16, 32, 56));
        TextoApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApellidoActionPerformed(evt);
            }
        });

        TextoWeb.setEditable(false);
        TextoWeb.setBackground(new java.awt.Color(255, 255, 255));
        TextoWeb.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoWeb.setForeground(new java.awt.Color(16, 32, 56));
        TextoWeb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        areaBiografia.setBackground(new java.awt.Color(255, 255, 255));
        areaBiografia.setColumns(20);
        areaBiografia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        areaBiografia.setForeground(new java.awt.Color(16, 32, 56));
        areaBiografia.setRows(5);
        areaBiografia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        jScrollPane4.setViewportView(areaBiografia);

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(TextoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setOpaque(false);

        TextoDesc.setEditable(false);
        TextoDesc.setBackground(new java.awt.Color(255, 255, 255));
        TextoDesc.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoDesc.setForeground(new java.awt.Color(16, 32, 56));
        TextoDesc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        TextoTipo.setEditable(false);
        TextoTipo.setBackground(new java.awt.Color(255, 255, 255));
        TextoTipo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoTipo.setForeground(new java.awt.Color(16, 32, 56));
        TextoTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        TextoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTipoActionPerformed(evt);
            }
        });

        TextoEntrada.setEditable(false);
        TextoEntrada.setBackground(new java.awt.Color(255, 255, 255));
        TextoEntrada.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TextoEntrada.setForeground(new java.awt.Color(16, 32, 56));
        TextoEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        listaPropuestas.setBackground(new java.awt.Color(255, 255, 255));
        listaPropuestas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaPropuestas.setForeground(new java.awt.Color(16, 32, 56));
        listaPropuestas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropuestasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaPropuestas);

        textoEstado.setEditable(false);
        textoEstado.setBackground(new java.awt.Color(255, 255, 255));
        textoEstado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoEstado.setForeground(new java.awt.Color(16, 32, 56));
        textoEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));

        listaUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        listaUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaUsuarios.setForeground(new java.awt.Color(16, 32, 56));
        listaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listaUsuarios);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("PROPUESTAS");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 32, 56));
        jLabel4.setText("COLABORADORES");

        textoRecaudado.setEditable(false);
        textoRecaudado.setBackground(new java.awt.Color(255, 255, 255));
        textoRecaudado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        textoRecaudado.setForeground(new java.awt.Color(16, 32, 56));
        textoRecaudado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 32, 56), 2, true));
        textoRecaudado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRecaudadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListaProponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaProponentesMouseClicked
        // TODO add your handling code here:
        proponente seleccionado = null;
        int i = ListaProponentes.getSelectedIndex();
        if(i >= 0){
        seleccionado = ic.listarProponentes().get(i); //ic.listar... devuelve una lista por eso luego .get ...
        }
        TextoNickname.setText(seleccionado.getNickname());
        TextoNombre.setText(seleccionado.getNombre());
        TextoApellido.setText(seleccionado.getApellido());
        labelFoto.setIcon(seleccionado.bytesAIcon());
        //TextoBiografia.setText(seleccionado.getBiografia());
        areaBiografia.setText(seleccionado.getBiografia());
        TextoWeb.setText(seleccionado.getLink());
        
        //ahora mostrar las propuestas.
        //podria mostrar todas las propuestas relacionadas a el y iterar y mostrar.
        List<propuesta> lista = new ArrayList<>();
        for(propuesta p : ic.listarPropuestas()){
           if(p.getProponente() == seleccionado.getNickname()){ //getproponente me da el nickname.
           lista.add(p);
           }
        }
        
        //ahora en listapropuestas mostrarlas todas. prox paso.
        modeloPropuesta.clear();
        listaPropuestas.setModel(modeloPropuesta); //intento usar mismo modelo.
        for(propuesta p : lista){
        modeloPropuesta.addElement(p.getTitulo());
        }
        
    }//GEN-LAST:event_ListaProponentesMouseClicked

    private void TextoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNicknameActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoApellidoActionPerformed

    private void TextoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTipoActionPerformed

    private void listaPropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropuestasMouseClicked
        // TODO add your handling code here:
        propuesta seleccionada = null;
        
        String titulo = listaPropuestas.getSelectedValue();
        
        for(propuesta p : ic.listarPropuestas()){
        if(p.getTitulo().contains(titulo)){
        seleccionada = p;
        break;
        }
        }
        
        TextoDesc.setText(seleccionada.getDescripcion());
        TextoTipo.setText(seleccionada.getTipo());
        TextoEntrada.setText(String.valueOf(seleccionada.getEntrada()));
        textoRecaudado.setText(seleccionada.getRecaudado().toString());
        textoEstado.setText(seleccionada.getEstadoActual().toString());
        
        //ahora tengo q mostrar los usuarios q colaboraron con p en listaUsuarios.
        
        //de propuesta, obtener las colaboraciones a ella y de cada colab obtener el colaborador para listarlo capaz.
        
        modeloUsuarios.clear();
        listaUsuarios.setModel(modeloUsuarios);
        for(colaboracion c : ic.listarColaboraciones()){
        if(c.getPropuesta().getTitulo().equalsIgnoreCase(titulo)){ //titulo o p.getTitulo capaz.
        //ahora get nombre proponente y agregarlo a la lista.
        modeloUsuarios.addElement(c.getColaborador().getNickname());
        }
        }
        
    }//GEN-LAST:event_listaPropuestasMouseClicked

    private void textoRecaudadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRecaudadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRecaudadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaProponentes;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTextField TextoApellido;
    private javax.swing.JTextField TextoDesc;
    private javax.swing.JTextField TextoEntrada;
    private javax.swing.JTextField TextoNickname;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoTipo;
    private javax.swing.JTextField TextoWeb;
    private javax.swing.JTextArea areaBiografia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JTextField textoEstado;
    private javax.swing.JTextField textoRecaudado;
    // End of variables declaration//GEN-END:variables
}
