/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;
import logica.colaborador;
import logica.propuesta;
import logica.colaboracion;

import logica.usuario;

import java.util.List;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;

public class PanelDejarSeguir extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultaColaborador
     */
    
    ictrl ic;
    
    List lista = null;
    DefaultListModel<String> modelo = new DefaultListModel<>();
    DefaultListModel<String> modelo2 = new DefaultListModel<>();
    
    public PanelDejarSeguir(ictrl ic, javax.swing.JPanel contenido) {
        initComponents();
        this.ic = ic;
        ListaSeguidor.setModel(modelo);
        for(usuario u : ic.listarUsuarios()){
        modelo.addElement(u.getNickname());
        }
        
        ListaSeguido.setModel(modelo2);
        for(usuario u2 : ic.listarUsuarios()){
        modelo2.addElement(u2.getNickname());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSeguidor = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaSeguido = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        botonSeguir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 32, 56));
        jLabel1.setText("SEGUIMIENTO USUARIOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("ESTE USUARIO DEJA DE SEGUIR");

        ListaSeguidor.setBackground(new java.awt.Color(255, 255, 255));
        ListaSeguidor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaSeguidor.setForeground(new java.awt.Color(16, 32, 56));
        ListaSeguidor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaSeguidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSeguidorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSeguidor);

        ListaSeguido.setBackground(new java.awt.Color(255, 255, 255));
        ListaSeguido.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ListaSeguido.setForeground(new java.awt.Color(16, 32, 56));
        ListaSeguido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaSeguido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaSeguidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaSeguido);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 32, 56));
        jLabel3.setText("ESTE VA A PERDER UN SEGUIDOR");

        botonSeguir.setBackground(new java.awt.Color(16, 32, 56));
        botonSeguir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonSeguir.setForeground(new java.awt.Color(255, 255, 255));
        botonSeguir.setText("DEJAR DE SEGUIR");
        botonSeguir.setBorderPainted(false);
        botonSeguir.setContentAreaFilled(false);
        botonSeguir.setOpaque(true);
        botonSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(botonSeguir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel3)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(botonSeguir)
                .addContainerGap(414, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListaSeguidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSeguidorMouseClicked
        // TODO add your handling code here:
     
        
        
    }//GEN-LAST:event_ListaSeguidorMouseClicked

    private void ListaSeguidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaSeguidoMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_ListaSeguidoMouseClicked

    private void botonSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirActionPerformed
        // TODO add your handling code here:
        
        String seguidor = null;
        String seguido = null;
        
        //guardo seguidor y seguido
        seguidor = ListaSeguidor.getSelectedValue();
        seguido = ListaSeguido.getSelectedValue();
        
        if(seguidor == null || seguido == null){
        JOptionPane.showMessageDialog(this, "Usuario inexistente.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
        }
        if(seguidor.equals(seguido)){
        JOptionPane.showMessageDialog(this, "No puedes dejar de seguirte a vos mismo.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        ic.dejarSeguir(seguidor, seguido);
        javax.swing.JOptionPane.showMessageDialog(this, "Seguimiento retirado.");

        
    }//GEN-LAST:event_botonSeguirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaSeguido;
    private javax.swing.JList<String> ListaSeguidor;
    private javax.swing.JButton botonSeguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
