/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */

import logica.ictrl;
import logica.fabrica;

import persistencia.ControladoraPersistencia;

import java.awt.CardLayout; //para pasar como en paginas
import java.awt.Image;
import javax.swing.ImageIcon;

public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    
    private ictrl ic;
    private fabrica fab;
    
    private CardLayout c1; //card para contenido
    
    private CardLayout p1; //card para toda la pantalla
    
    public Pantalla() {
        initComponents(); 
        this.fab = new fabrica();
        this.ic = fab.getIctrl();
        
        c1 = new CardLayout();
        
        contenido.setLayout(c1);
        contenido.add(principal, "principal");
        c1.show(contenido, "principal");
        
        p1 = new CardLayout();
        
        PantallaGrandePrincipal.setLayout(p1);
        PantallaGrandePrincipal.add(PanelPrincipal, "principal");
        p1.show(PantallaGrandePrincipal, "principal");
        
        ImageIcon icon = new ImageIcon("src/Imagenes/logo.png");
        Image img = icon.getImage().getScaledInstance(portaIcono.getWidth(), portaIcono.getHeight(), Image.SCALE_SMOOTH);
        portaIcono.setIcon(new ImageIcon(img));
        portaIcono.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaGrandePrincipal = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        principal = new javax.swing.JPanel();
        portaIcono = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonSistema = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonPropuestas = new javax.swing.JButton();
        botonColaboraciones = new javax.swing.JButton();
        botonLaWeb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setSize(new java.awt.Dimension(1600, 900));

        PanelPrincipal.setBackground(new java.awt.Color(16, 32, 56));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CULTURARTE");

        contenido.setPreferredSize(new java.awt.Dimension(1280, 900));

        principal.setBackground(new java.awt.Color(255, 240, 255));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portaIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portaIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo300.png"))); // NOI18N
        principal.add(portaIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(119, 205, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CULTURARTE");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        botonSistema.setBackground(new java.awt.Color(119, 205, 215));
        botonSistema.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonSistema.setForeground(new java.awt.Color(255, 255, 255));
        botonSistema.setText("CARGAR DATOS DE PRUEBA");
        botonSistema.setBorder(null);
        botonSistema.setContentAreaFilled(false);
        botonSistema.setOpaque(true);
        botonSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSistemaActionPerformed(evt);
            }
        });

        botonUsuarios.setBackground(new java.awt.Color(119, 205, 215));
        botonUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuarios.setText("USUARIOS");
        botonUsuarios.setBorder(null);
        botonUsuarios.setContentAreaFilled(false);
        botonUsuarios.setOpaque(true);
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¡Bienvenido!");

        botonPropuestas.setBackground(new java.awt.Color(119, 205, 215));
        botonPropuestas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonPropuestas.setForeground(new java.awt.Color(255, 255, 255));
        botonPropuestas.setText("PROPUESTAS");
        botonPropuestas.setBorder(null);
        botonPropuestas.setContentAreaFilled(false);
        botonPropuestas.setOpaque(true);
        botonPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPropuestasActionPerformed(evt);
            }
        });

        botonColaboraciones.setBackground(new java.awt.Color(119, 205, 215));
        botonColaboraciones.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonColaboraciones.setForeground(new java.awt.Color(255, 255, 255));
        botonColaboraciones.setText("COLABORACIONES");
        botonColaboraciones.setBorder(null);
        botonColaboraciones.setContentAreaFilled(false);
        botonColaboraciones.setOpaque(true);
        botonColaboraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColaboracionesActionPerformed(evt);
            }
        });

        botonLaWeb.setBackground(new java.awt.Color(119, 205, 215));
        botonLaWeb.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        botonLaWeb.setForeground(new java.awt.Color(255, 255, 255));
        botonLaWeb.setText("LA WEB");
        botonLaWeb.setBorder(null);
        botonLaWeb.setContentAreaFilled(false);
        botonLaWeb.setOpaque(true);
        botonLaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLaWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonColaboraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonPropuestas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLaWeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonLaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addComponent(contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PantallaGrandePrincipalLayout = new javax.swing.GroupLayout(PantallaGrandePrincipal);
        PantallaGrandePrincipal.setLayout(PantallaGrandePrincipalLayout);
        PantallaGrandePrincipalLayout.setHorizontalGroup(
            PantallaGrandePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PantallaGrandePrincipalLayout.setVerticalGroup(
            PantallaGrandePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaGrandePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaGrandePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSistemaActionPerformed
        // TODO add your handling code here:
        //c1.show(contenido, "principal");
        
        if(ic.listarUsuarios().isEmpty()){ //condicion basica para no hacerlo. sino habria q guardar un bool en la bd etc ...
        
        ic.cargoUsuarios();
        
        ic.cargoSeguidores();
        
        ic.cargoTipos();
        
        ic.cargoPropuestas();
        
        ic.cargoColaboraciones();
        
        }
        
    }//GEN-LAST:event_botonSistemaActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        // TODO add your handling code here:
        PanelUsuarios panelUsuarios = new PanelUsuarios(ic, p1, PantallaGrandePrincipal);
        PantallaGrandePrincipal.add(panelUsuarios, "panelUsuarios");
        p1.show(PantallaGrandePrincipal, "panelUsuarios");
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPropuestasActionPerformed
        // TODO add your handling code here:
        PanelPropuestas panelPropuestas = new PanelPropuestas(ic, p1, PantallaGrandePrincipal);
        PantallaGrandePrincipal.add(panelPropuestas, "panelPropuestas");
        p1.show(PantallaGrandePrincipal, "panelPropuestas");
    }//GEN-LAST:event_botonPropuestasActionPerformed

    private void botonColaboracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColaboracionesActionPerformed
        // TODO add your handling code here:
        PanelColaboraciones panelColaboraciones = new PanelColaboraciones(ic, p1, PantallaGrandePrincipal);
        PantallaGrandePrincipal.add(panelColaboraciones, "panelColaboraciones");
        p1.show(PantallaGrandePrincipal, "panelColaboraciones");
    }//GEN-LAST:event_botonColaboracionesActionPerformed

    private void botonLaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLaWebActionPerformed
        // TODO add your handling code here:
        PanelLaWeb PanelLaWeb = new PanelLaWeb(ic, p1, PantallaGrandePrincipal);
        PantallaGrandePrincipal.add(PanelLaWeb, "PanelLaWeb");
        p1.show(PantallaGrandePrincipal, "PanelLaWeb");
    }//GEN-LAST:event_botonLaWebActionPerformed

    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PantallaGrandePrincipal;
    private javax.swing.JButton botonColaboraciones;
    private javax.swing.JButton botonLaWeb;
    private javax.swing.JButton botonPropuestas;
    private javax.swing.JButton botonSistema;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel portaIcono;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
