/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-23 01:12:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import logica.Inscripcion_general;
import logica.Inscripcion_paquete;
import logica.Turista;
import logica.EstadoActividad;
import logica.ActividadTuristica;
import java.util.Collection;
import logica.Proveedor;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import controladores.ISistema;
import controladores.Fabrica;
import datatypes.DataUsuario;
import controladores.Fabrica;
import controladores.ISistema;
import controladores.Fabrica;
import controladores.ISistema;
import datatypes.DataUsuario;

public final class consultausuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Components/header.jsp", Long.valueOf(1697146746000L));
    _jspx_dependants.put("/Components/bodyFinal.jsp", Long.valueOf(1696857816000L));
    _jspx_dependants.put("/Components/bodyPrincipal.jsp", Long.valueOf(1697428284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("logica.Turista");
    _jspx_imports_classes.add("logica.EstadoActividad");
    _jspx_imports_classes.add("logica.Inscripcion_paquete");
    _jspx_imports_classes.add("datatypes.DataUsuario");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("logica.Inscripcion_general");
    _jspx_imports_classes.add("logica.ActividadTuristica");
    _jspx_imports_classes.add("logica.Proveedor");
    _jspx_imports_classes.add("controladores.ISistema");
    _jspx_imports_classes.add("controladores.Fabrica");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("        <title>Turismo</title>\n");
      out.write("\n");
      out.write("        <!-- Custom fonts for this template-->\n");
      out.write("        <link href=\"ComponentsBoostrap/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link\n");
      out.write("            href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\n");
      out.write("            rel=\"stylesheet\">\n");
      out.write("        <!-- Custom styles for this template-->\n");
      out.write("        <link href=\"ComponentsBoostrap/css/sb-admin-2.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"Components/estilos.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("  ");
 
    ISistema sys = new Fabrica().getSistema();
  
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Object loggeadoAtributo = session.getAttribute("logeado");
    DataUsuario usuarioLoggeado = null;
    ISistema sys2 = new Fabrica().getSistema();
    boolean logged = false;
    String nick = null;
    
    if (loggeadoAtributo != null) {
        logged = (boolean) loggeadoAtributo;
    }

    if (logged) {
        nick = (String) session.getAttribute("nick");
        usuarioLoggeado = sys2.verInfoUsuarioNick(nick);
           
        
    }

      out.write("\n");
      out.write("\n");
      out.write("<body id=\"page-top\">\n");
      out.write("\n");
      out.write("    <!-- Page Wrapper -->\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("        <!-- Sidebar -->\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- Sidebar - Brand -->\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.jsp\">\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\n");
      out.write("                    <i class=\"fas fa-tree\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">Turismo.uy </div>\n");
      out.write("\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\n");
      out.write("\n");
      out.write("            <!-- Nav Item - Dashboard -->\n");
      out.write("            \n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("            <!-- Heading -->\n");
      out.write("            <div class=\"sidebar-heading\">\n");
      out.write("                Gestion\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\n");
      out.write("\n");
      out.write("                <!-- Usuarios -->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUsuarios\"\n");
      out.write("                       aria-expanded=\"true\" aria-controls=\"collapseUsuarios\">\n");
      out.write("                        <span>Usuarios</span>\n");
      out.write("                    </a>\n");
      out.write("                    <div id=\"collapseUsuarios\" class=\"collapse\" aria-labelledby=\"headingUsuarios\"  data-parent=\"#accordionSidebar\">\n");
      out.write("                        <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                            <a class=\"collapse-item\" href=\"usuarios\">Ver usuarios</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Paquetes -->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePaquetes\"\n");
      out.write("                       aria-expanded=\"true\" aria-controls=\"collapsePaquetes\">\n");
      out.write("                        <span>Paquetes</span>\n");
      out.write("                    </a>\n");
      out.write("                    <div id=\"collapsePaquetes\" class=\"collapse\" aria-labelledby=\"headingPaquetes\" data-parent=\"#accordionSidebar\">\n");
      out.write("                        <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                            \n");
      out.write("           \n");
      out.write("                                     ");

                                if (logged && sys2.getTipo(usuarioLoggeado.getNick()).equals("turista")) {
                            
      out.write("\n");
      out.write("                            <a class=\"collapse-item\" href=\"comprapaquete\">Compra de paquete</a>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                           \n");
      out.write("                            <a class=\"collapse-item\" href=\"paquetes\">Consultas de paquete <br> de actividades turísticas</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Salidas Turísticas -->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseSalidas\"\n");
      out.write("                       aria-expanded=\"true\" aria-controls=\"collapseSalidas\">\n");
      out.write("                        <span>Salidas Turísticas</span>\n");
      out.write("                    </a>\n");
      out.write("                    <div id=\"collapseSalidas\" class=\"collapse\" aria-labelledby=\"headingSalidas\" data-parent=\"#accordionSidebar\">\n");
      out.write("                        <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                    \n");
      out.write("                            \n");
      out.write("                                  ");

                                if (logged && sys2.getTipo(usuarioLoggeado.getNick()).equals("proveedor")) {
                            
      out.write("\n");
      out.write("                            <a class=\"collapse-item\" href=\"SvAltaSalidaTuristica\">Alta de salida Turística</a>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                            \n");
      out.write("                           \n");
      out.write("                            <a class=\"collapse-item\" href=\"salidasturisticas\">Consulta de salida Turística</a>\n");
      out.write("                          \n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                                                 ");

                                if (logged && sys2.getTipo(usuarioLoggeado.getNick()).equals("turista")) {
                            
      out.write("\n");
      out.write("                            <a class=\"collapse-item\" href=\"salidasturisticas\">Inscripción a salida Turística</a>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <hr class=\"sidebar-divider\">\n");
      out.write("                <!-- Actividades Turísticas -->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseActividades\"\n");
      out.write("                       aria-expanded=\"true\" aria-controls=\"collapseActividades\">\n");
      out.write("                        <span>Actividades Turísticas</span>\n");
      out.write("                    </a>\n");
      out.write("                    <div id=\"collapseActividades\" class=\"collapse\" aria-labelledby=\"headingActividades\" data-parent=\"#accordionSidebar\">\n");
      out.write("                        <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                                                ");

                                if (logged && sys2.getTipo(usuarioLoggeado.getNick()).equals("proveedor")) {
                            
      out.write("\n");
      out.write("                            <a class=\"collapse-item\" href=\"crearactividad\">Alta de actividades turísticas</a>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                           \n");
      out.write("                            \n");
      out.write("                            <a class=\"collapse-item\" href=\"actividadestur\">Consulta de actividades</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Divider -->\n");
      out.write("                <hr class=\"sidebar-divider d-none d-md-block\">\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("        <!-- End of Sidebar -->\n");
      out.write("\n");
      out.write("        <!-- Content Wrapper -->\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\n");
      out.write("\n");
      out.write("            <!-- Main Content -->\n");
      out.write("            <div id=\"content\">\n");
      out.write("\n");
      out.write("                <!-- Topbar -->\n");
      out.write("                <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\n");
      out.write("\n");
      out.write("                    <!-- Sidebar Toggle (Topbar) -->\n");
      out.write("                    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\n");
      out.write("                        <i class=\"fa fa-bars\"></i>\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <!-- Topbar Search -->\n");
      out.write("                    <form\n");
      out.write("                        class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\"\n");
      out.write("                                   aria-label=\"Search\" aria-describedby=\"basic-addon2\">\n");
      out.write("                            <div class=\"input-group-append\">\n");
      out.write("                                <button class=\"btn btn-primary\" type=\"button\">\n");
      out.write("                                    <i class=\"fas fa-search fa-sm\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("\n");
      out.write("                    <!-- Topbar Navbar -->\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("\n");
      out.write("                                            <!-- Nav Item - User Information -->\n");
      out.write("                          <li class=\"nav-item dropdown no-arrow\">\n");
      out.write("                                ");

                                    
                                    String pfpUsuario = "img/user-not-verified.png";
                                   
                                
                                    if (logged) {
                                        if(usuarioLoggeado.getImagenP() != null){
                                        pfpUsuario = usuarioLoggeado.getImagenP();
                                    }
                                
      out.write("\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\n");
      out.write("                                   data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                    <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">\n");
      out.write("                                        ");
      out.print(nick);
      out.write("\n");
      out.write("                                        ");
} else {
      out.write("\n");
      out.write("                                        <a class=\"nav-link\" href=\"login\" id=\"iniciarSesionBtn\" role=\"button\"\n");
      out.write("                                           aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                            <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">\n");
      out.write("                                                Iniciar sesión");
}
      out.write("\n");
      out.write("\n");
      out.write("                                            </span>\n");
      out.write("                                            <img class=\"img-profile rounded-circle\"\n");
      out.write("                                                 src=\"");
if (logged) {
      out.print(pfpUsuario);
} else {
      out.write("img/user-not-verified.png");
}
      out.write("\">\n");
      out.write("                                        </a>\n");
      out.write("                                    <!-- Dropdown - User Information -->\n");
      out.write("                                    <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n");
      out.write("                                         aria-labelledby=\"userDropdown\">\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"modificarusuario\">\n");
      out.write("                                            <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("                                            Modificar datos\n");
      out.write("                                        </a>\n");
      out.write("                                       \n");
      out.write("                                        <div class=\"dropdown-divider\"></div>\n");
      out.write("                                        <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\n");
      out.write("                                            <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("                                            Logout\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    ");
 if (!logged) {
      out.write("\n");
      out.write("                                    <li class=\"nav-item  no-arrow\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <a class=\"nav-link\" href=\"registrarse\" id=\"iniciarSesionBtn\" role=\"button\"\n");
      out.write("                                           aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                            <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">\n");
      out.write("                                                Registrarse\n");
      out.write("                                            </span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    ");
}
      out.write("\n");
      out.write("                                    </ul>\n");
      out.write("\n");
      out.write("                                    </nav>\n");
      out.write("                                    <!-- Begin Page Content -->\n");
      out.write("                                    <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <!-- Footer -->\n");
      out.write("                                        <footer class=\"sticky-footer bg-white\">\n");
      out.write("                                            <div class=\"container my-auto\">\n");
      out.write("                                                <div class=\"copyright text-center my-auto\">\n");
      out.write("\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>");
      out.write('\n');

    String nickUsuario = (String) request.getParameter("nick");
    
    DataUsuario usr = null;
    try {
        usr = sys.verInfoUsuarioNick(nickUsuario);
    } catch (Exception e) {}
    LocalDate fecha = LocalDate.parse(usr.getFecNac());
    // Define un formato personalizado "dia-mes-año"
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    // Formatea la fecha en el formato deseado
    String fecnac = fecha.format(formato);

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <title>Usuario ");
      out.print( nickUsuario );
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
 if (usr.getImagenP() != null) { 
      out.write("\n");
      out.write("    <img class=\"imgPerfil\" src=\"");
      out.print( usr.getImagenP() );
      out.write("\"/>\n");
 } 
      out.write("\n");
      out.write("<h1>");
      out.print( nickUsuario );
      out.write("</h1>\n");
      out.write("<p>Email: ");
      out.print( usr.getCorreo() );
      out.write("</p>\n");
      out.write("<p>Tipo: ");
      out.print( usr.getTipo() );
      out.write("</p>\n");
      out.write("<p>Nombre: ");
      out.print( usr.getNombre() );
      out.write("</p>\n");
      out.write("<p>Apellido: ");
      out.print( usr.getApellido() );
      out.write("</p>\n");
      out.write("<p>Fecha de Nacimiento: ");
      out.print( fecnac );
      out.write("</p>\n");
 if (usr.getTipo().equals("Turista")) { 
      out.write("\n");
      out.write("    <p>Nacionalidad: ");
      out.print( usr.getNacionalidad() );
      out.write("</p>\n");
      out.write("    <hr>\n");
      out.write("    <h5>Inscripciones Generales:</h5>\n");
      out.write("        ");
 Turista t =(Turista) Proveedor.obtenerUsuario(usr.getCorreo());
        Collection<Inscripcion_general> inscripcion_general = t.getInscripciongeneral();
        for(Inscripcion_general insGnl : inscripcion_general){
            if(insGnl != null && usr.getNick().equals(nick)){
        
      out.write("   \n");
      out.write("            <br>\n");
      out.write("            <p>Inscripcion a Salida: ");
      out.print( insGnl.getSalida().getNombreSalida() );
      out.write("</p>\n");
      out.write("            <p>Costo: ");
      out.print( insGnl.getCostoGeneral() );
      out.write("</p>\n");
      out.write("            <p>Cantidad de turistas: ");
      out.print( insGnl.getCantidad() );
      out.write("</p>\n");
      out.write("            <p>Inscripcion a Salida: ");
      out.print( insGnl.getFechaCompra() );
      out.write("</p>\n");
      out.write("            <p><a href=\"salida?nombre=");
      out.print(insGnl.getSalida().getNombreSalida() );
      out.write("\">-Info</a></p>\n");
      out.write("        ");
  
            }
        }
    
      out.write("\n");
      out.write("    <hr>\n");
      out.write("    <h5>Inscripciones a Paquetes:</h5>\n");
      out.write("    ");

        Collection<Inscripcion_paquete> inscripcion_paquete = t.getInscripcionpaquete();
        for(Inscripcion_paquete insPaq : inscripcion_paquete){
            if(insPaq != null && usr.getNick().equals(nick)){
        
      out.write("   \n");
      out.write("            <br>\n");
      out.write("            <p>Inscripcion a Salida: ");
      out.print( insPaq.getPaquete().getNombre_paquete() );
      out.write("</p>\n");
      out.write("            <p>Costo: ");
      out.print( insPaq.getCostoPaquete() );
      out.write("</p>\n");
      out.write("            <p>Cantidad de turistas: ");
      out.print( insPaq.getCantidad() );
      out.write("</p>\n");
      out.write("            <p>Inscripcion a Salida: ");
      out.print( insPaq.getVencimiento() );
      out.write("</p>\n");
      out.write("            <p><a href=\"paquetes?nombrePaq=");
      out.print(insPaq.getPaquete().getNombre_paquete() );
      out.write("\">-Info</a></p>\n");
      out.write("        ");
  
            }
        }
    
      out.write(' ');
      out.write('\n');
 } else if (usr.getTipo().equals("Proveedor")) { 
      out.write("\n");
      out.write("    <p>Descripcion: ");
      out.print( usr.getDescripcion() );
      out.write("</p>\n");
      out.write("    <p>Sitio web: <a href=\"");
      out.print( usr.GetWeb() );
      out.write("\" target=\"blank\"> ");
      out.print( usr.GetWeb() );
      out.write("</a></p>\n");
      out.write("    <p>Actividades que provee:</p>\n");
      out.write("    <ul>\n");
      out.write("    ");
 Proveedor p =(Proveedor ) Proveedor.obtenerUsuario(usr.getCorreo());
        Collection<ActividadTuristica> acts = p.getActTuristica();
        String estado = "";
        for(ActividadTuristica act : acts){
        if(act.getEstado() == EstadoActividad.CONFIRMADA || usr.getNick().equals(nick)){
        if(usr.getNick().equals(nick)){
        estado =" -Estado: "+ act.getEstado().toString();
        }
    
      out.write("    \n");
      out.write("\n");
      out.write("    <li>");
      out.print( act.getNombre());
      out.write(' ');
      out.print(estado);
      out.write(" <a href=\"actividad?actNombre=");
      out.print(act.getNombre());
      out.write("\">-Info</a></li>\n");
      out.write("            ");
} }
      out.write('\n');
 } 
      out.write("\n");
      out.write("</ul>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("            \n");
      out.write("                                            </footer>\n");
      out.write("                                            <!-- End of Footer -->\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- End of Content Wrapper -->\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- End of Page Wrapper -->\n");
      out.write("\n");
      out.write("                                        <!-- Scroll to Top Button-->\n");
      out.write("                                        <a class=\"scroll-to-top rounded\" href=\"#page-top\">\n");
      out.write("                                            <i class=\"fas fa-angle-up\"></i>\n");
      out.write("                                        </a>\n");
      out.write("\n");
      out.write("                                        <!-- Logout Modal-->\n");
      out.write("                                        <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                                             aria-hidden=\"true\">\n");
      out.write("                                            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                                <div class=\"modal-content\">\n");
      out.write("                                                    <div class=\"modal-header\">\n");
      out.write("                                                        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\n");
      out.write("                                                        <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                                                            <span aria-hidden=\"true\">×</span>\n");
      out.write("                                                        </button>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\n");
      out.write("                                                    <div class=\"modal-footer\">\n");
      out.write("                                                        <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                                                        <form action=\"SvLogout\" method=\"post\" >\n");
      out.write("                                                        <button type=\"submit\" class=\"btn btn-primary\" >Logout</button>\n");
      out.write("                                                        </form>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <!-- Bootstrap core JavaScript-->\n");
      out.write("                                        <script src=\"ComponentsBoostrap/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("                                        <script src=\"ComponentsBoostrap/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("                                        <!-- Core plugin JavaScript-->\n");
      out.write("                                        <script src=\"ComponentsBoostrap/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("                                        <!-- Custom scripts for all pages-->\n");
      out.write("                                        <script src=\"ComponentsBoostrap/js/sb-admin-2.min.js\"></script>\n");
      out.write("\n");
      out.write("                                        <!-- Page level plugins -->\n");
      out.write("                                        <script src=\"ComponentsBoostrap/vendor/chart.js/Chart.min.js\"></script>\n");
      out.write("\n");
      out.write("                                        <!-- Page level custom scripts -->\n");
      out.write("                                        <script src=\"ComponentsBoostrap/js/demo/chart-area-demo.js\"></script>\n");
      out.write("                                        <script src=\"ComponentsBoostrap/js/demo/chart-pie-demo.js\"></script>\n");
      out.write("\n");
      out.write("                                        </body>\n");
      out.write("\n");
      out.write("                                        </html>");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
