/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-10-17 06:24:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class altaPerfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession sesion = request.getSession(false);
    String rol = null;
    String usuario = null;

    if (sesion != null) {
        rol = (String) sesion.getAttribute("rol");
        usuario = (String) sesion.getAttribute("usuarioLogueado");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Alta de perfil</title>\n");
      out.write("        <style>\n");
      out.write("        body {\n");
      out.write("font-family: Arial, sans-serif;\n");
      out.write("margin:0;\n");
      out.write("background:#f5f7fa;\n");
      out.write("}\n");
      out.write("        header {\n");
      out.write("background:#2c3e50;\n");
      out.write("color:white;\n");
      out.write("padding:15px 25px;\n");
      out.write("display:flex;\n");
      out.write("justify-content:space-between;\n");
      out.write("align-items:center;\n");
      out.write("}\n");
      out.write("        header h1 {\n");
      out.write("margin:0;\n");
      out.write("font-size:20px;\n");
      out.write("}\n");
      out.write("        nav a {\n");
      out.write("color:white;\n");
      out.write("margin:0 10px;\n");
      out.write("text-decoration:none;\n");
      out.write("}\n");
      out.write("        nav a:hover {\n");
      out.write("text-decoration:underline;\n");
      out.write("}\n");
      out.write("        .container {\n");
      out.write("padding:30px;\n");
      out.write("}\n");
      out.write("        .card {\n");
      out.write("background:white;\n");
      out.write("border-radius:8px;\n");
      out.write("box-shadow:0 2px 6px rgba(0,0,0,0.1);\n");
      out.write("padding:25px;\n");
      out.write("max-width:600px;\n");
      out.write("margin:0 auto;\n");
      out.write("}\n");
      out.write("        h2 {\n");
      out.write("color:#2c3e50;\n");
      out.write("margin-bottom:15px;\n");
      out.write("}\n");
      out.write("        p {\n");
      out.write("margin:8px 0;\n");
      out.write("}\n");
      out.write("        #entrada {\n");
      out.write("margin:10px 10px 10px 0;\n");
      out.write("padding:8px;\n");
      out.write("width:95%;\n");
      out.write("border:1px solid #ccc;\n");
      out.write("border-radius:5px;\n");
      out.write("}\n");
      out.write("        #tipo {\n");
      out.write("margin-top: 10px;\n");
      out.write("padding:8px;\n");
      out.write("border-radius:5px;\n");
      out.write("}\n");
      out.write("        .cardContra {\n");
      out.write("background:white;\n");
      out.write("border-radius:8px;\n");
      out.write("box-shadow:0 2px 6px rgba(0,0,0,0.1);\n");
      out.write("padding:10px;\n");
      out.write("margin-top:15px;\n");
      out.write("}\n");
      out.write("        button {\n");
      out.write("background:#3498db;\n");
      out.write("color:white;\n");
      out.write("border:none;\n");
      out.write("border-radius:5px;\n");
      out.write("padding:10px 20px;\n");
      out.write("cursor:pointer;\n");
      out.write("}\n");
      out.write("        button:hover {\n");
      out.write("background:#2980b9;\n");
      out.write("}\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <header>\n");
      out.write("        <h1>🌐 Culturarte</h1>\n");
      out.write("        <nav>\n");
      out.write("            <a href=\"index.jsp\">🏠 Inicio</a>\n");
      out.write("\n");
      out.write("            ");
 if (usuario != null && !"visitante".equalsIgnoreCase(rol)) {
      out.write("\n");
      out.write("            <span style=\"margin-right:10px;\">👤 ");
      out.print( usuario);
      out.write("</span>\n");
      out.write("            <a href=\"logout\">🚪 Cerrar Sesión</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("            <a href=\"altaPerfil.jsp\">🆕 Crear Cuenta</a>\n");
      out.write("            <a href=\"inicioSesion.jsp\">🔑 Iniciar Sesión</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </nav>\n");
      out.write("    </header> \n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h2>🆕 Alta de Perfil</h2>\n");
      out.write("                <form action=\"altaPerfilServlet\" method=\"POST\" enctype=\"multipart/form-data\">\n");
      out.write("                    \n");
      out.write("                    <input id=\"entrada\" type=\"text\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nickname\" required><br>\n");
      out.write("                    <input id=\"entrada\" type=\"text\" name=\"nombre\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nombre\" required><br>\n");
      out.write("                    <input id=\"entrada\" type=\"text\" name=\"apellido\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.apellido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Apellido\" required><br>\n");
      out.write("                    <input id=\"entrada\" type=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Email\" required><br>\n");
      out.write("\n");
      out.write("                    <!-- 📅 Fecha de nacimiento -->\n");
      out.write("                    <input id=\"entrada\" type=\"date\" name=\"fechaNacimiento\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.fechaNacimiento}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required><br>\n");
      out.write("\n");
      out.write("                    <!-- 🖼️ Imagen -->\n");
      out.write("                    <input id=\"entrada\" type=\"file\" name=\"imagen\" accept=\"image/*\" required><br>\n");
      out.write("\n");
      out.write("                    <select name=\"tipo\" id=\"tipo\" onchange=\"mostrarCamposExtras()\">\n");
      out.write("                        <option value=\"colaborador\">Colaborador</option>\n");
      out.write("                        <option value=\"proponente\">Proponente</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <div id=\"extraProponente\" style=\"display:none;\">\n");
      out.write("                        <input id=\"entrada\" type=\"text\" name=\"direccion\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.direccion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Dirección\">\n");
      out.write("                        <input id=\"entrada\" type=\"text\" name=\"biografia\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.biografia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Biografía\">\n");
      out.write("                        <input id=\"entrada\" type=\"text\" name=\"sitioWeb\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.sitioWeb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Sitio web\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"cardContra\">\n");
      out.write("                        <input id=\"entrada\" type=\"password\" name=\"contrasena\" placeholder=\"Contraseña\" required>\n");
      out.write("                        <input id=\"entrada\" type=\"password\" name=\"confirmacion\" placeholder=\"Confirmación de contraseña\" required>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button type=\"submit\">✅ Crear Perfil</button>\n");
      out.write("\n");
      out.write("                    ");
 if (request.getAttribute("mensaje") != null) { 
      out.write("\n");
      out.write("                        <div style=\"color:red; margin-top:10px;\">\n");
      out.write("                            ");
      out.print( request.getAttribute("mensaje") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("        function mostrarCamposExtras() {\n");
      out.write("            const tipo = document.getElementById(\"tipo\").value;\n");
      out.write("            const extra = document.getElementById(\"extraProponente\");\n");
      out.write("            const inputs = extra.querySelectorAll(\"input\");\n");
      out.write("\n");
      out.write("            if (tipo === \"proponente\") {\n");
      out.write("                extra.style.display = \"block\";\n");
      out.write("                inputs.forEach(i => i.required = true);\n");
      out.write("            } else {\n");
      out.write("                extra.style.display = \"none\";\n");
      out.write("                inputs.forEach(i => i.required = false);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", mostrarCamposExtras);\n");
      out.write("        document.getElementById(\"tipo\").addEventListener(\"change\", mostrarCamposExtras);\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
